### PR TITLE
LPS-69483 Wrong url in email notification when the blog entry is published by admin impersonating another user

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

As you advised in https://github.com/robertoDiaz/liferay-portal/pull/518#issuecomment-276016858, I added the fix to Wikis and Message Boards since the error was reproducible on these places as well.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi

Im dealing with a criticar issue and I didnt had time to review this today.

Tomorrow I Will have time.

Sorry for the delay!

**Comment by IstvanD** [comment]
Hi,

No problem, thanks for the notice!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3764. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3805. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
