### PR TITLE
LPS-86455 - save generation status of previews

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-86455

Hi @robertoDiaz,

This is the fix that we discussed here in the SME request [LPP-32516](https://issues.liferay.com/browse/LPP-32156). It creates a new table "DLPreview". I attempted to cover all documents that generate previews (although the error reported in LPP-31835 and, therefore by extension, LPS-86455 only technically applies to PDFs). The fix for the LPS itself is in commit a63ee94. Please let me know if you have any questions or suggestions for improvement. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @wanderlast 

As explained in https://loop.liferay.com/web/guest/home/-/loop/feed/14955839 I was on vacation. I'll try to review this today or tomorrow.

Thanks!!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
