### PR TITLE
[TS] LPS-73336

### PR DESCRIPTION
**Pull request by yuhai**
Hi Roberto,

Based on https://github.com/robertoDiaz/liferay-portal/pull/577#pullrequestreview-46792747, I resubmit the fix.

If you have other concerns, please let me know.

Regards,
Hai

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
hey @yuhai 

CI is broken, I'll review this and retry the test with my PR

Thanks!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3925. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/34217f4db7da~3...34217f4db7da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3926. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/387a19c346cc~4...387a19c346cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
