### PR TITLE
LPS-108862 SF - Inline

### PR DESCRIPTION
**Pull request by adolfopa**
@robertoDiaz I've made quite some changes on top of yours. Can you double chekc everything is fine?

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85928.

**Pull request closed without merging**
