### PR TITLE
[TECHNICAL-SUPPORT] LPS-69486 Notification delivery email checkbox gets ignored for private messages

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull?

It applies a condition check in `sendEmail()` which is present in `sendNotificationEvent()` (basically applying the changes of [SOS-2173](https://issues.liferay.com/browse/SOS-2173) in the other method).

Thank you.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
hey @IstvanD 

Some concerns about the pr.

The first think is why aren't we using the SubscriptionSender as we do in other parts of the portal (I guess that this is because this portlet was a plugin). Anyway, since this is an implementation detail, I've check what we to in SubscriptionSender to handle this in this other cases, and it seems weird to me have 3 clauses in the if.

I think that this:

``` 
                        if ((userThread.getUserId() == mbMessage.getUserId()) ||
				((userThread.getUserId() != mbMessage.getUserId()) &&
				 !UserNotificationManagerUtil.isDeliver(
					 userThread.getUserId(),
					 PrivateMessagingPortletKeys.PRIVATE_MESSAGING,
					 PrivateMessagingConstants.NEW_MESSAGE, 0,
					 UserNotificationDeliveryConstants.TYPE_EMAIL))) {

				continue;
			}
```
should become into this:

```
                       if (!UserNotificationManagerUtil.isDeliver(
					 userThread.getUserId(),
					 PrivateMessagingPortletKeys.PRIVATE_MESSAGING,
					 PrivateMessagingConstants.NEW_MESSAGE, 0,
					 UserNotificationDeliveryConstants.TYPE_EMAIL)) {

				continue;
			}
```

Why do we need this extra clauses? I mean, if a user configures that he doesn't what to receive emails, our logic should only consider this clause. Doesn't this make more sense?

Maybe there's something I'm missing, so could you clarify this??

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

The extra clauses are necessary because otherwise the message sender would also receive a notification email, not just the recipient.

**Comment by robertoDiaz** [comment]
Ok, I see. 

I remember that this feature was also included in the SSender.  (see LPS-48484)

IMHO, your logic is fine, but, since not use the SSender for this case seems to be technical debt,  could be better if we use it as we do in most portal cases.

I think it's not very hard to implement, and will simplify the logic, since we are going to use a common pattern. Do you agree?

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I agree that SubscriptionSender should be eventually used for notifications on private messages, however, I think such a change would merit to be done in it's own LPS, and, unfortunately, I don't have the time to make it.
Also, because this is a customer reported issue, I'm pretty much in a hurry fixing it :)

**Comment by robertoDiaz** [comment]
hey @IstvanD, 

Ok. I've talk with @adolfopa  and collab team is changing the SSender use pattern, so your pr is fine for them.

I'm going to send the pr to @adolfopa in order to push this to master.

Thank you!!

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/413. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Thank you @robertoDiaz !

**Pull request closed without merging**
