### PR TITLE
[TECHNICAL-SUPPORT] LPS-95366 When document upload fails in Documents and Media, it leaves an overlay in the DOM

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @robertoDiaz ,

[LPS-95366](https://issues.liferay.com/browse/LPS-95366),

See LPS for reproduction. Please review it.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Hey @robertoDiaz 

The SF wants me to break up the language key. It would make it harder to find the langkey trough search. Can we push it forward?

Thanks,

**Comment by robertoDiaz** [comment]
Hi @NemethNorbert ,

We could not pass it if it has SF problems.

Anyway, why is this a problem, if it could not be reproduced using a vanilla installation??

Did I miss something?

One last thing. In Java, a RuntimeException it's an unpredictable exception and it doesn't have semantics, so I do not understand why should we have to handle it. It's a kind of fatal error that could not be predicted... IMHO, this is not a bug, and we should not fix it.

Thanks!!

**Comment by NemethNorbert** [comment]
Hey @robertoDiaz,

Regarding SF -> I'll update the PR.

Regarding the issue -> I agree that the issue is on the edge in case of wether it is a bug or not. I'd rather just call it poor error handling. I understand that we should not handle RuntimeExceptions, but how should we communicate it to the frontend, if we received an unexpected error during upload?

My reasoning behind this change is that even if this error is only reproducible with custom code that triggers an unexpected RuntimeException, the UI still breaks and the only solution I found is to handle this kind of exception as well. I agree we should not handle all RuntimeException, but it might worth to handle in this scenario, given the fact that it breaks the UI and the solution is simple.

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hey @NemethNorbert 

>  I agree that the issue is on the edge in case of wether it is a bug or not. I'd rather just call it poor error handling.

If liferay do not throw the RuntimeException OOTB, where is the error or the poor error handling??

**Comment by NemethNorbert** [comment]
Hey @robertoDiaz,

You are right, I don't know wether the runtime exception was thrown from custom code or from liferay because of a custom code,  when the customer found this issue.

I think the fix is simple and has a low risk to cause regression. RuntimeException is something that we don't have to handle,  however it doesn't mean we cannot. In this case I decided to take an extra mile and in the meantime make DM more robust. I cannot bring more reasons up why we should merge this.
Feel free to close or forward the PR. I'll handle the LPP and LPS accordingly.

Thanks,

**Comment by robertoDiaz** [comment]
Closing. 

See the LPP for extra info

**Pull request closed without merging**
