### PR TITLE
LPS-70045 No permission check exists for attachments

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Attachment folders have no permission checking which results that an unauthorized user can access the contents of that folder if they are accessed though a direct link, like a preview URL or a download URL.

File entries that are attachments of an asset - like MB Messages or Wiki pages -, reside in attachment folders and are served by `WebServerServlet.sendPortletFileEntry()`

I added code that checks the permission for the attachment folder the requested file entry resides in. It checks if the user has view permission for the asset the attachment belong to.
I implemented only the case when the asset is an MB Message, because I could not refer to the WikiPage classname, which resides in a separate module. Other asset types may also have attachments.

I want to make this solution more general so that it doesn't relies on concrete classnames like MBMessage, but instead works for arbitrary asset types with attachments.

Do you have an idea how to achieve this?

Thank you in advance!

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
I think that include something like this in DLFileEntryPermission could make the trick:

`String className = dlFileEntry.getClassName();
		long classPK = dlFileEntry.getClassPK();

		if (className != null) {
			if (!BaseModelPermissionCheckerUtil.containsBaseModelPermission(
					permissionChecker, dlFileEntry.getGroupId(), className,
					classPK, actionId)) {

				return false;
			}
		}`

Tomorrow I'll test it.

Anyway, this could be considered a new feature, so I need to check with the product team if we should fix this.

Thanks!!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Many thanks, I'm looking forward for the results.

Bests,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/32. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/13804a6b7481~4...13804a6b7481) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
