### PR TITLE
LPS-102179 Not possible to create shortcuts to files from a different site in Documents and Media

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @robertoDiaz 

Could you please review this pull request?

The root cause of the issue is, that when an arbitrary folder has been chosen as the DM portlet's root folder, and not the current site is selected while creating a shortcut, the portlet will search in the configured root folder on the other site, where it doesn't exist.

The solution: If another site is selected, the portlet's configured root folder should be reset (eg. change it's folderId to 0).
 
Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Could you please share the results of your review of this solution?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Yes,

Why do we have to pass a folder=0 as parameter??

0 is the default value, so if we don't pass it the value of this variable should be 0 in the action, isn't it?

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

The folderId parameter is utilized in edit_file_entry.jsp, among others
https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/edit_file_entry.jsp#L39

If you debug this part, you will see, that folderId will be the ID of the configured root folder. If no root folder was configured, indeed, the folderId will be 0, but if one is set, the folderId will be that of the root folder. 
Because the root folder belongs to the current site, not to the site that was set to search for the file to be shortcutted, the folderId has to be explicitly set to 0.

Best regards,
István

**Comment by robertoDiaz** [comment]
Got it @IstvanD, 

I have another question, 

Where do we set this root folder as a value for folderId?

Is it possible that this new site has a root folder that is not the default one (i mean "0")?  If that's the case we should not use this value but the configured 

Regards

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

The folderId is set in DLAdminDisplayContext
https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/display/context/DLAdminDisplayContext.java#L296

As to your second question, I'll check that possibility.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Please let me know if you have additional questions.

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/1113. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/23762852ca36~1...23762852ca36)

**Pull request closed without merging**
