### PR TITLE
LPS-73946 When a user has many connections and the Microblogs portlet is added to a page, rendering it takes a lot of time

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

I added a method to the JSONWS API, so the elements are accessed as a collapsed JSON array, instead of an expanded one, that had led to an increased minification time in case of a large set of connections.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I think we should not use the service this way, and we should avoid change the API for wrong reasons.

IMHO, this method ( com.liferay.microblogs.util.MicroblogsUtil#getJSONRecipients) should have never been in microblogs-service but in microblogs-web bundle, since seems to be used only by the view. It's kind of jsp implementation detail.

Following this thoughts, i think that we should not include a call from the service to this logic. Don't you agree?

I think that you have included that call to the service only because you can call it using JSONWS, but I think we have better choices. I think we can use the same approach (load the elements Async) using a ResourceAction.

I'm going to do a test ASAP following this idea.

What do you think?

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I agree that the approach is far from perfect.
The goal is basically to prevent the situation where a huge JSON array literal is being rendered in `edit_microblogs_entry.jsp` thus being clogged in the minification proccess in `GoogleJavaScriptMinifier.compress(String resourceName, String content)`

Instead of the array literal, the array variable would be rendered, so the whole page would retain a constant size regardless of the array's size.

I have thought about resourceURL's, they are used in Calendar for example, but I'm not that much familiar with the concept.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I am wondering if you could test the alternative method using a ResourceAction?

Thanks!

Best regards,
István

**Comment by robertoDiaz** [comment]
Not yet, since I've been busy

could you handle this?

The idea is to use a ResourceAction to obtain the results, instead of the WS call.

We are doing something similar in other parts of the portal, for example "users-admin-web/../resources/view.jsp"

```
function <portlet:namespace />getUsersCount(className, ids, status, callback) {
		AUI.$.ajax(
			'<liferay-portlet:resourceURL id="/users_admin/get_users_count" />',
			{
				data: {
					className: className,
					ids: ids,
					status: status
				},
				success: callback
			}
		);
	}
```

The action should have a "doServeResource" that returns the results calling the Util Method

**Comment by robertoDiaz** [comment]
you could also check how is implemented the "AutocompletePageTitleMVCResourceCommand" where we are returning  a json and with it we form a new html

**Comment by IstvanD** [comment]
Thanks, I'll try these approaches.

**Pull request closed without merging**
