### PR TITLE
Lps 182691 followup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @shuyangzhou 

It is not working, AMImageMagickImageScaler is not been registered.

If you don't mind I'll follow @adolfopa suggested change: https://github.com/liferay-lima/liferay-portal/pull/4283#pullrequestreview-1417946369

**Comment by shuyangzhou** [comment]
@robertoDiaz it works fine for me.
`g! services (objectClass=com.liferay.adaptive.media.image.scaler.AMImageScaler)
{com.liferay.adaptive.media.image.scaler.AMImageScaler}={component.id=6367, component.name=com.liferay.adaptive.media.image.internal.scaler.AMDefaultImageScaler, service.id=3913, supportedMimeTypes=*, service.scope=bundle, service.bundleid=1359}
  "Registered by bundle:" com.liferay.adaptive.media.image.impl_5.0.43 [1359]
  "Bundles using service"
    com.liferay.adaptive.media.image.impl_5.0.43 [1359]
{com.liferay.adaptive.media.image.scaler.AMImageScaler}={component.id=6368, component.name=com.liferay.adaptive.media.image.internal.scaler.AMGIFImageScaler, service.id=4574, supportedMimeTypes=image/gif, service.scope=bundle, service.bundleid=1359}
  "Registered by bundle:" com.liferay.adaptive.media.image.impl_5.0.43 [1359]
  "Bundles using service"
    com.liferay.adaptive.media.image.impl_5.0.43 [1359]
{com.liferay.adaptive.media.image.scaler.AMImageScaler}={component.id=6374, component.name=com.liferay.adaptive.media.image.internal.scaler.AMImageMagickImageScaler, service.id=5241, supportedMimeTypes=[image/avif,image/gif,image/heic,image/tiff,image/webp], service.scope=bundle, service.pid=com.liferay.adaptive.media.image.internal.configuration.AMImageMagickConfiguration, service.bundleid=1359}
  "Registered by bundle:" com.liferay.adaptive.media.image.impl_5.0.43 [1359]
  "Bundles using service"
    com.liferay.adaptive.media.image.impl_5.0.43 [1359]
`

How did you test it?

In https://github.com/liferay-lima/liferay-portal/pull/4283 , it has both functional issues and design issue.

1.  It can not do modified here. https://github.com/liferay-lima/liferay-portal/pull/4283/commits/1d5853ae91b3990bae6c15458e87ec10ad3323a2#diff-4dfdf36cd868fdc0d5b7d3c79bd2b9dac0a9d24156e80b09611eb4e070c081aaR79 In case modified does happen, you will be leaking ServiceTrackerMap, no one will close it.
2. In https://github.com/liferay-lima/liferay-portal/pull/4283/commits/1d5853ae91b3990bae6c15458e87ec10ad3323a2#diff-775acb94fac29b6c1fef3c11e085302c7c972b5eacc294f746fe87a3614d1421R48, AMImageMagickImageScaler does not have mime type tags, which means consumer other than AMImageScalerRegistryImpl won't be able to filter it by type, for example here https://github.com/robertoDiaz/liferay-portal/pull/896/commits/2c11b31af331c7a0b59b76dc058b68c4b4913ce4#diff-6ff75e3beb24ed88ccb9bcdb3052a33df79eb930ce3cca5d192407d069eae249R126
3. https://github.com/liferay-lima/liferay-portal/pull/4283/commits/1d5853ae91b3990bae6c15458e87ec10ad3323a2#diff-4dfdf36cd868fdc0d5b7d3c79bd2b9dac0a9d24156e80b09611eb4e070c081aaR92 is a design problem. AMImageScalerRegistryImpl is the collector here, it should not know the exact type of the elements it collects. This creates a bad dependency from design's point of view.

Please test this pull again, if still having issues, let me know how do you test it.

**Comment by robertoDiaz** [comment]
Hey @shuyangzhou ,

I've done a quick test with an empty database and now it seems to work. 👍 

With the same steps now I get 6 image scalers (as expected):

Captura de pantalla 2023-05-09 a las 16 49 03

I'm going to do more tests and check if everything works as expected.

Thank you for your help!

**Comment by robertoDiaz** [comment]
ci:help

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
