### PR TITLE
[TECHNICAL-SUPPORT] LPS-70254 Screen name gets cropped from mentionee nameplate if full name is too long

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull?

Thanks in advance!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

If you find the time, could you please check this pull request?
Thank you in advance!

Bests,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Sure, sorry for the delay.

I was in LA and I didn't had enough time to check the pr.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

No problem.
Please let me know if you have questions or need any help-

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I could not find any commit with LPS-70254.

Could you clarify what should I review?

**Pull request merged**
