### PR TITLE
LPS-83373 In Wiki pages, list subitems within <ol type="a"> become numbered

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @robertoDiaz 

The santitizer issue [LPS-83129](https://issues.liferay.com/browse/LPS-83129) has been resolved, but there still exists a bug in the Wiki component.
After publishing a Wiki page containing nested lists, the bulleting style appears to be digits even when the type is specified to alphabetical.
This is because decimal bullet points are explicitly declared in the stylesheet for nested lists in Wiki pages.

```
.portlet-wiki {
	.wiki-body {
		ol ol {
			list-style: decimal outside;
		}
```

The code was entered via [LPS-18926](https://issues.liferay.com/browse/LPS-18926). The cannot be reproduced in DXP/master, even when LPS-18926 is reverted. Therefore, I'm reverting LPS-18926 as it's no longer needed, and it solves the current issue.

Thanks, and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Can you create a unit test?

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I would create one, however, in contrast to LPS-83129, this change has no affect on the code of the Wiki content. It affects only how the published pages are rendered by the browser, due to a stylesheet imported in the page.
As I know, this can be only tested manually.

Best regards,
István

**Comment by IstvanD** [comment]
OK, I'll do so.

**Comment by IstvanD** [comment]
Sent to https://github.com/sergiogonzalez/liferay-portal/pull/4522

**Pull request closed without merging**
