### PR TITLE
[TECHNICAL-SUPPORT] LPS-69693 Disable heading text formatting in Wiki editor for Creole

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

Unfortunately, [LPS-69693](https://issues.liferay.com/browse/LPS-69693) was incomplete, and I had to extend it with an additional use case.
Please see [LPS-69693](https://issues.liferay.com/browse/LPS-69693) for details.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
@IstvanD 

Could you check if the broken test are real errors??

If not, just reopen.

Thx!

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I made source formatting changes to the code and resened the pull as https://github.com/robertoDiaz/liferay-portal/pull/514

However, this pull has been also closed for failing tests, but for now, I could determine what the reason for the failing was.
I reopened  https://github.com/robertoDiaz/liferay-portal/pull/514 just now, and observer if it will be closed again.

**Pull request closed without merging**
