### PR TITLE
LPS-72359

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49131 thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49190. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/045948f6b6ee~3...045948f6b6ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/553. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/647d2a3e9131~4...647d2a3e9131) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/560. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/f9888cb1afdf~2...f9888cb1afdf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49316. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/68549eff20a5~3...68549eff20a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
