### PR TITLE
LPS-76632 Get all the social activities for the 'All' tab

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

Could you please review my fix suggestion for LPS-76632?

Thank you,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
It seems that the behaviour change is not right.

I've made an analysis of the file history and I've found this logic ( see 6.2 - activities/view.jsp):

`if (group.isUser()) {
	activities = SocialActivityLocalServiceUtil.getUserActivities(group.getClassPK(), 0, max);
}`

(In master the service and them method name has been changed to a new name pattern (from SocialActivity to SocialActivitySet) but it behaves the same.)

It means that if this portlet is in a user group (my dashboard returns true to this clause) we should only show the current user activities, so it seems that it is working as expected in current master and this is not a bug.

Anyway  If I've miss anything, please tell me.

Maybe you could create a new SME request in order to open a new conversation with the Product team in order to obtain more information related with this, but as said, based in the history of the logic, it doesn't look as a bug.

Thanks!!

**Comment by hudakl** [comment]
Hi,

I doublechecked the behavior of the Acitivities and based on my findings I still think this is a bug.

I found that if we add the portlet to an arbitrary page it indedd goes to the Scope.ALL branch of the if-statements in the SocialActivitiesQueryHelper.getSocialActivitySets method and selects the group Activities. I also noticed that in this case the other tabs are not available so it could only display the Activities of the current site.

In case the Activities portlet is on the 'My Dashboard' page only then is possible to select the All tab at all. You're saying that since the scope group here is group belonging to the current user so we should select only current user's activities. But as I see the 'Me' tab is for that purpose. With the current behavior we have two tabs containing exactly the same entries. Plus the 'All' tab-title clearly suggests that we're supposed to see every user's every activity (filtered by a permission check of course).

So, in light of this I think we should consider the current behavior as a bug.
What's your opinion on that?

Thanks,
Laci

**Comment by robertoDiaz** [comment]
Hi again.

Fist of all, I do not think that show all the activities in a page restricted to the user scope makes sense. This pages are designe to show user's content and information, and it seems that this portlet was adapted to behave as that when located there (in 6.2.x it does).

In DXP it has suffered a redesign and some tabs were added (i think it was because some of them were in Social Office).

So in one hand we have a portlet that when it's located in 'My Dashboard' is restricted to user activities and in the other hand we have added more functionality to it, and maybe some of this functionalities are not designed to 'My Dashboard' view and we should hide them in this case.

Because of that I tend to think that maybe what is wrong is to show the all tab in this kind of pages, because as you said "all" tabs has the meaning of show all the new activities and not only the ones scoped to the current user.

Please open a new SME request in order to agree a solution, because I suspect that the all tab (and maybe others) was/were not designed to be in 'My Dashboard' or similar places.

Thanks!

**Comment by hudakl** [comment]
I've opened the SME request.

**Pull request closed without merging**
