### PR TITLE
LPS-98952 Asset owner can modify and delete another user's comment on the asset

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

Thank you and best regards,
István

> I added the Owner and Admin condition. Original behavior doesn't change. If you are the owner of the document, you still can edit or delete all comments. But if the admin changes the comment rules from Control Panel->Configurations ->System Settings ->Comments :
> 
> 1 disable edit other comments: Owner still can modify and delete own comments, but he can't modify other users comments
> 2 disable delete other comments: Owner still can delete and modify own comments, but he can't delete other users comments
> 
> 3 Disable both: Owner modifies and deletes only own comments.

@MarcellGyopos

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by MarcellGyopos** [comment]
> Hey @MarcellGyopos
> 
> For this cases it's better to create 2 commits (It's easier to review if the original changes are separated from the autogenerated ones)
> 
> 1 for the original change, and 1 for "gradlew buildLang"
> 
> Can you split this commit in 2?

Hi @robertoDiaz ,

I do not understand what you mean, please be more specific. The second commit contains the language files.

**Comment by MarcellGyopos** [comment]
> > Hey @MarcellGyopos
> > For this cases it's better to create 2 commits (It's easier to review if the original changes are separated from the autogenerated ones)
> > 1 for the original change, and 1 for "gradlew buildLang"
> > Can you split this commit in 2?
> 
> Hi @robertoDiaz ,
> 
> I do not understand what you mean, please be more specific. The second commit contains the language files.

Ah, I get you now, back then I haven't known about the buildLang command, that's why I solved it manually and put it to one commit.

**Comment by robertoDiaz** [comment]
Hi,

After a deeper analysis, i think that we can't do this:

This this PR we are creating a new way to control if asset owners can edit/remove the comments, but we are still using the old mechanism, the permission check.

If we do so, it is possible to avoid asset owners with deletion permissions delete comments (wich is a bug) or just the opossite.

I think that we have the current mechanism (the permission check) but do not use it at entity level but service level. To do so we have to move the entity permissions to be portlet permissions.

For example the default.xml for blogs should be: https://gist.github.com/robertoDiaz/081e4e1428c00ecf009e162d47257119

We have to do this in all the applications, and it is most probable that we have to create an upgrade process in order to honor the current permissions.

As a second step we should move the discussion.comments.always.editable.by.owner property to system settings and change it's value.

Anyway, I'm not sure if this is backporteable, so, for the current customer, since he is able to do what he wants, we should inform him about how to do this OOTB and do not provide a hotfix.

Regards

**Comment by MarcellGyopos** [comment]
> we should inform him about how to do this OOTB and do not provide a hotfix.

 Hi @robertoDiaz 
 
 If I am not mistaken you say that my solution is not complete because it overrides the original permission system. We should use the current one instead and extend entity permission to portlet level permission with default.xml and with a certain upgrade process.

 Can you tell me about this upgrade process?  Where can I find an example?
 What do you mean by that "since he is able to do what he wants"?
 Can the customer make this change without our modifications?
 
 Regards,
 Marci

**Pull request closed without merging**
