### PR TITLE
LPS-70544 Document can be searched even if the Doc type is changed and the attribute should not be existing

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull?

Issue and solution details are described in the LPS.

Thank you,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I think that copyfileEntryMetadata method is there in order to allow WebDAV and Sync copy this metadata, so I think that this changes are breaking their logic and tiding the service with our web form.

Maybe, in this case we could remove the old metadata, but in my opinion it doesn't seem to be the right solution.

Today I'm out of time, but tomorrow I'll work a little more on this. 

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Thanks for the explanation.

During every document update, metadata will be copied from the old version to the new.
The problem is, even the metadata that doesn't applies to the new version anymore (because, for example, the old version contains a field that the new one doesn't contain any more) will be copied,

**Comment by robertoDiaz** [comment]
Yes, I'm working on this, since there are some concerns about WebDav and Sync that we should take care in this pull.

For example, I've discover a bug regarding WebDav (if you modify a file using WebDav instead of web interface we change the fileEntryType to Basic because we aren't passing the old value.

So, your logic needs to have a valid "fileEntryTypeId" attribute set in the service context and we have to add it in the case of webdav.

I'm checking if we have the same use case in Sync.

ASAP I've finished with the changes I'll let you know

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/491. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/89bf1d4~2...89bf1d4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
