### PR TITLE
LPS-83129 In HTML Wikis, subitems within <ol type="a"> become numbered after publishing

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

As you requested in https://github.com/robertoDiaz/liferay-portal/pull/704#issuecomment-401705454, I added a test that tests the nested ordered list numbering style.

I don't know if it is in the correct test class though.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hi @IstvanD,

Thank you for the update.

I've checked the changes a little bit and I think that we could use another approach.

The problem here is that we are changing the antisamy configuration for all the apps, and not just for wiki.

Currently we have a limitation that do not allow to set antisamy configurations per application, so It's safer to disallow a single app than change rules for all the apps.

So, I'd suggest to whitelist the wiki in the antisamy configuration if the user needs it and do not modify our security policy for content.

What do you think of that?

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Thank you for looking into this.
The customer was suggested previously to whitelist Wiki pages, but they declined this approach since it would pose a security risk for them, as nearly all of their contents are published as Wiki pages.

As I see, Journal Articles are whitelisted by default, but when I remove the class from the whitelist, the issue can be reproduced there too.

**Comment by robertoDiaz** [comment]
Please see the jira ticket for more info.

**Pull request closed without merging**
