### PR TITLE
[TECHNICAL-SUPPORT] LPS-68499 Asset names are localized in email notifications

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull?

The problem is that if someone gets mentioned on a blog post (with `@username`) and receives an email, the recipient will get a localized version of the asset name. The translation depends on the locale the user who submitted the blog post.

The email templates are _asset_entry_mention_email_body.tmpl_ and _asset_entry_mention_email_subject.tmpl_ are hardcoded English text, while they contain a localizable placeholders

`[$USER_NAME$] Mentioned You in a [$ASSET_ENTRY_NAME$]`

Since it is English text, the asset names should be also English to keep it consistent.

Another approach would be for the templates to be localized, but then all templates should be written/generated in each language.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
I think is is wrong since it should be translated to the receiver language, not a default one.

I'm working in a similar fix for MB that consist in pass to the subscription sender a set of localized context attributes that will be translated to the same language as the message

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

It would be indeed a more logical behavior for the asset name appear in the recipients language. 
The problem is, that the email templates are currently available in only one language, English.

In {{DefaultMentionsNotifier.notify()}} there may be multiple recipients set (they are in mentionedUsersScreenNames), with each of them with their own locale, but there in only one temple for email body, and one temple for email subject, both available only in English. 

Is there a way to apply the idea in the fix you mentioned, for this current situation?

Thank you!

**Comment by robertoDiaz** [comment]
I've made a preliminar analysis and it seems that the subjectLocalizedValuesMap and bodyLocalizedValuesMap parameter are the email body and subjects in different languages, so the message is translated.

With your changes, I think that the body and the subject could be, for example, in spanish, but the  asset name will allways be in english. Is it wrong, or I'm missing something?

**Comment by IstvanD** [comment]
Based on their names they supposed to be translated, but according to debugging, they have the following structure:

LocalizedValuesMap
-- _defaultValue: Dear [$TO_NAME$]  ...
-- _values: {zh_CN=null, es_ES=null, ja_JP=null, iw_IL=null, nl_NL=null, fi_FI=null, ca_ES=null, hu_HU=null, fr_FR=null, en_US=null, pt_BR=null, de_DE=null}

LocalizationImpl checks or the localized value in _values, map, and if it isn't there, then it chooses the default, which is _defaultvalue.

The question is, when LocalizedValuesMap gets initialized, when should be the non-default (non-English) values be inserted?

I've set the locale of the portal to hu_Hu (Hungarian), and debugged LocalizationImpl.getMap()

```
	@Override
	public Map<Locale, String> getMap(LocalizedValuesMap localizedValuesMap) {
		Map<Locale, String> map = localizedValuesMap.getValues();

		Locale locale = LocaleUtil.getDefault();

		if (map.get(locale) == null) {
			map.put(locale, localizedValuesMap.getDefaultValue());
		}
```

locale is hu_HU, but the map doesn't contains the translation for this language, so the default English value will be put in the map, and the map return with it..

**Comment by robertoDiaz** [comment]
Oh, I see...

In fact we both are right...

All the backed is prepared for i18n the body and the subject but there is a missing User Interface to set the different body/subjects in each lang.

I've talk with the Collab team and they are going to analyze how to solve this.

Unfortunatelly this is going to be considered a new feature and will not be introduced in DXP.

I think that your pr is not the right solution (the good one is allow create the body/subject in different langs), but at least is more consistent than the current behaviour where we could find different langs in a single message.

BTW, same is happening for comments.

Could you resend this to @sergiogonzalez?

**Comment by IstvanD** [comment]
hey @robertoDiaz 

I opened the pull for @sergiogonzalez 
https://github.com/sergiogonzalez/liferay-portal/pull/3510

**Pull request closed without merging**
