### PR TITLE
LPS-124848

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz

I have rebased the changes on master.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I rebased the solution on the latest status of master.
Please note that the current solution still erases the blog subscriptions, as their classname IDs are being overwritten.
https://github.com/robertoDiaz/liferay-portal/pull/863/commits/0105fdacebe854dae084766d6c64cdadbd84cc8f

**Comment by robertoDiaz** [comment]
Yes,

We have a peak of tickets in Spain, that's why I didn't had time to work on this

**Comment by IstvanD** [comment]
@robertoDiaz I understand. No pressure.

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I'm aware that your team has probably still many tickets on the plate.
But by any chance, could you find the time to complete the review?

If so, I'm looking forward to the pull request with the changes.

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Not yet, we are really busy this days, this is in my queue, but we have other tasks with more priority. I'll try to pass this tomorrow or monday if I have a chance.

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/137. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/64b34df1b954~4...64b34df1b954)

**Pull request closed without merging**
