### PR TITLE
LPS-93391 Correcting usage of MBDiscussionGroupServiceConfiguration

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I made corrections to `MBDiscussionGroupServiceConfiguration` and moved some of the classes to follow the pattern of other `GroupServiceConfiguration` and `ConfigurationCategory` classes. I also moved the templates from the core to the **message-boards-api** project.

It is working now.

Please let me know what you think of this.

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Does the solution looks fine to you?
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I'm modifiying some packages and moving the configuration files. I'll send it to @adolfopa today

Thanks!!

**Comment by IstvanD** [comment]
OK, thanks for letting me know!

Best regards,
István

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/78. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/094f1e3c1cee~4...094f1e3c1cee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
