### PR TITLE
LPS-110189 If the SMTP service is provided by Microsoft Office 365 and starttls is not enabled, the mail transmission will fail with "com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP" regardless of the transport protocol

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @robertoDiaz 

I have tested the solution and came to the conclusion that Office 365 won't let through any mail which `starttls.enable` property is not **true** (although I admit, it's weird in my opinion too). Therefore, I changed the condition to check if the SMTP provider is Office 365. Maybe this would look better with using a String constant.

Also, I removed the part of `MailMessageListener` that sets the From Address to the value of `mail.session.mail.smtp.user` as I realized that a custom From Address may be enabled in the Administration of the Office 365 service.

Please let me know what you think.

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I pushed the requested changes.

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1357. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/7341c60fa9a1~1...7341c60fa9a1)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/99. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/7341c60fa9a1~1...7341c60fa9a1)

**Pull request closed without merging**
