### PR TITLE
LPS-99173 Use BlogsEntryServiceUtil

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @robertoDiaz 

Could you please review this pull request?

Since `BlogsEntryServiceUtil.getGroupUserEntries()` might return more than 1 result, I modified the condition checks.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

What do you think, can we go with this solution?

Best regards,
István

**Comment by robertoDiaz** [comment]
Hi @IstvanD

I'm not sure, I do not fully understand why we need the if clause. IMHO seems a little bit "tricky"

Can you explain it to me??

I'll review and test this tomorrow.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

If the selection method is set to "User" in Recent Bloggers portlet, the user will only see blog posts of the site where the blogger posted last. And that site may not be visible to the user.

For example, userA and userB and members of siteA, but userA is also a member of siteB.
userA posts on siteA, userB sees it. Then, userA posts on siteB, and userB cannot see it, nor the previous posts of userA, because the Recent Bloggers now shows posts of userA only from siteB (since thats where userA posted last).

Ergo the Recent Bloggers portlet can show blog entries only from one site.

That is why I though that instead of userB presented nothing, he still could see userA's blog posts from SiteA.

I'm open to other solutions if you find this too "tricky".

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Thank you for the info.

I think that I do understand it now.

Anyway, I'm not sure about what's the expected behavior, so I'm going to test it.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
If I understand it well the problem is that we are showing elements from groups that the current user can’t see. Is it ok?

With this continue logic, we’ll iterate  the statsUsers until we find something we could see

Fallback to the current group doesn’t seem to be a “solution”:

Imagine that the user1 creates blog entries in 5 groups, in this order: A,B,C,D,E and User 2 is able to see B, and E

User 2 uses the recent blogs porlet in E

1. With current master logic, the portlet will show the A,B,C,D,E blog entries (is it ok?)
2. With PR logic it seems that the portlet will show the E,B,E,E,E (I can’t see any logic to prevent it)
3. I think that the expected behavior is show B and E, wich seems to be the expected behavior.

In order to do this we could check if the user has permissions to see the group and continue if not.

Can you check it?

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I'll check it.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

The recent bloggers portlet will show only one post per user.
Since it was user1 who posted on all 5 groups, the portlet will show user1's post on group E, since that's the last group where he posted.
Also, the post count will be 1, because user1 made only one post on group E.

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/4lejandrito/liferay-portal/pull/318. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1064. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
