### PR TITLE
LPS-73550 Use title instead of filename because it's the information we display in the ui. Filename is internal.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55332. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
cc/ @sergiogonzalez

**Pull request closed without merging**
