### PR TITLE
[TECHNICAL SUPPORT] LPS-146530 Document Does Not Checkin after Edit in Office 365

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-146530](https://issues.liferay.com/browse/LPS-146530)

I'd like to start with the requirement to reproduce this issue is you will need a company account at Office 365 with active license to the programs like word. I had to request it trough IS and it took a bit of time.
In case you want just reach out to me and we can schedule a call for reproduction on my machine with my credentials.

About the issue: We are using effects in a functional component in a dangerous way.
When the user edits a document trough office 365, we will open a new tab and reload the documents and media page.
The problem here, is that our Liferay.component registered modal is still alive and its open method will reference setState methods that are not part of the current React component's scope.

As per [the react documentation about useEffect](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1) I refactored the code to make sure we handle this effect in our component proper lifecycles and also clean up after we unmount the react component.

Please review my change

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/liferay-lima/liferay-portal/pull/2702. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/686645e768d5~2...686645e768d5)

**Pull request closed without merging**
