### PR TITLE
LPS-82437 Creole Wiki: unordered lists copied from Google Docs lose formatting after switching between source and text editor

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

When creating a list in Google Docs, each line item will be enclosed in it's own paragraph element.

`<ul><li><p>One</p></li><li><p>Two</p><ul><li><p>Three</p></li><li><p>Four</p></li></ul></li><li><p>Five</p></li></ul>`

The cause the text processor to place two line breaks for each paragraph element in the source view, even when element is embedded in a list item element.

The resolution Creole code in the source view will be as follows:

```
*

One

*

Two

**

Three

**

Four
```

When switching back to text view, those separate lines are not interpreted as they were a list element anymore.

In contrast, when writing a list in GMail and pasting it to the Wiki editor, it keeps it's structure between the view switches, because the list item contents are not enclosed in paragraph tags.

The solution is to skip placing newlines for paragraph elements when it is detected that the paragraph element has a list element as one of it's ancestors.

Thank you of you review it.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
I'm not sure that this is a bug.

Why should we change the way we are handling the paragraph markup? I my opinion it works as expected and Google Docs is not generating it as it should.

Does it make sense?

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

The reason why I think this is a bug is because the user will experience a non-expected behavior when pasting the list to the Wiki editor and then switching between the text and source views.

When the user switches to source view, the generated Creole code will already make no sense, as the special characters (star, *) and the list item themselves will end up in their own lines. When switching back to text view, the result will be as follows:

list

The formatting and embedding will be lost, and the bullet point symbols will be converted to *-s.

When the user works handles the list, copies and pastes it in confine of the Google Docs app, they will perceive no error, no aware of the fact that paragraph elements enclose the list item. However, once they start to user the Wiki editor in Liferay and switches between the views, the structure of the list will be destroyed.

However, witch the modification I submitted here, the user can change the view back and forth, the list will stay intact.

I hope this convinces you that this is a bug and is worth fixing it on our side.

Best regards,
István

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

After reading your explanation I've understand that the error is not show it as it does (with the new line) but showing that in one case and not in other. Is it right?

I've also talked with @antoni-ortega about this and we agreed that change the behavior doesn't seem to be the best option. Maybe other users are expecting the current behaviour and we could broke their contents.

Instead of change the way we handle the markup, we could change the way we see the original pasted content, and show it as the editor does (I mean, process it once it is pasted).

In this case, the user will see it with the new lines in all the cases, but we are consistent and it is more obvious that Google Docs markup is the responsible of this behavior.

I you need fix guidance, open a new SME request. Antonio and I will handle it.

Regards!

**Pull request closed without merging**
