### PR TITLE
LPS-63360

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hi @JorgeFerrer , @arbetts,

I've test the solution but it doesn't work.

As you said the double escape is done by OSGi, so we could not avoid it. 

Anyway, due we are reading this default configuration directly in a wiki validation we should reproduce this double escape in our service. Anyway, it doesn't work in all the cases because if the preference is saved in DB it should not be scaped. 

So, if we use this approach the validator code will be conditional and really ugly.

Maybe we sould change this config method, width two different possibilities:

A. Delete pageTitlesRegexp, and pageTitlesRemoveRegexp configuration methods and registering new components with the validation logic, and use them in wiki.

B. Change the pageTitlesRegexp, and pageTitlesRemoveRegexp configuration methods to pageTitlesValidationClass and pageTitlesRemoveValidationClass allow the admin declare the Validator service that wiki will use, and implement it as components. Depending on the specified validator wiki will use it.

Sounds good to you??

**Comment by JorgeFerrer** [comment]
Hey Roberto,

I think that using a component for this, but it should be a component that does the Validation and normalization and that allows implementations different from using a Regexp. I'm not sure how much work that would be.

One other alternative that I just thought of is to stop using the default property of Meta.AD and instead automatically load a configuration with a .cfg file @csierra can provide the details about how to do that. In this case the default would be an empty string and the code should be able to handle that as "no normalization or validation is done", just in case an admin clicks "Reset Values" in System Settings and removes the auto loaded configuration.

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/jorgeferrer/liferay-portal/pull/674. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/72eff35~2...72eff35) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2949. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/a5c3a63~3...a5c3a63) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
