### PR TITLE
[TS] LPS-146666

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @robertoDiaz ,

Can you help review this PR?

Please let us know if you have any questions.
Thanks!

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-146666
> 
> The issue here was an infinite loop was caused when the default friendly URL was left empty. The reason this occurred is because the layoutId was being passed into layoutFriendlyURLEntryValidator.validateFriendlyURLEntry instead of the plid of the layout.
> To fix the issue, I passed the layout's plid when the friendly URL being validated belongs to an already existing layout. However, I also added an else statement to handle the validation when a new layout is being created.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hi @ericyanLr 

You could send this PRs to @liferay-lima since I'm part of the review process. (I'll forward this)

Thanks!

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/liferay-lima/liferay-portal/pull/2740. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/82de8d41454e~1...82de8d41454e)

**Pull request closed without merging**
