### PR TITLE
LPS-103335 Make sure the displayStyle of the Media Gallery is properly published in staging

### PR DESCRIPTION
**Pull request by hudakl**
Hi Roberto,

Could you please review my solution proposal for LPS-103335?

Thank you,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by hudakl** [comment]
Hi @robertoDiaz ,

Do you have any updates on the review?

Thanks,
Laci

**Comment by robertoDiaz** [comment]
Yes, I'm going to pass it today.

I had to talk with @cgoncas in order to have some information about the capability mechanism.

Regards.

**Comment by robertoDiaz** [comment]
Hey @hudakl 

Please check the SF (missing copyright, author, etc)

**Pull request closed without merging**
