### PR TITLE
LPS-68558 Translate body only if it's necessary

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull?
It is forwarded from https://github.com/IstvanD/liferay-portal/pull/23

Sorry for the numerous pull request lately.

Best regards,
István

### CODE REVIEW

**Comment by moltam89** [comment]
ci:reopen

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

do you have any update about this fix?

I don't think that the failing tests are related.

Thanks,
Tamás

**Comment by robertoDiaz** [comment]
Hi @moltam89,

Sorry, I missed this pr.

I'll review during this morning. Anyway, I've made a preliminar check and I do not fully understand why we should translate the message only when it is in bbcode.

Seems weird to me.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3519. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
