### PR TITLE
LPS-75064 Apache Tika parsing runs for uploaded LAR files

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I have made adjustments to MimeTypesImpl in order to make it valid for the tests.
The reason why it failed previously is because the call

`String extension = FileUtil.getExtension(fileName);`

would throw a NullPointerException because the fileImpl object wasn't initialized.
Therefore I added the method `_getFileNameExtension(String fileName)` that doesn't depend on that object.

I also adjusted MimeTypesImplTest to pass with the content types returned by tika-mimetypes.xml instead of analyzing the file content.

For the description of the rest of the code, please see https://github.com/robertoDiaz/liferay-portal/pull/606

Again, I'm not sure if this is the right approach, since there can be alternative solution like returning the application/zip type for all *.lar files.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Please let me know your thought about this solution.

Thank you!

Best regards,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD ,I was in the devcon so I could not review this before

I've check the logic, and even if it is functional and fixes the problem, it's too dark and hard to understand, so I'd preffer the simple approach since.

Also, seeying the changes in the test, we are changing the content types of some files, and this could break customers developements since they could be expected for the current content type and found a different one once this fix is applied.

So, could you resend with the simple approach? (that must not change the content types used in the tests)

Thanks!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

No worries. I realize I send many C&DM related pull requests these days, but unfortunately, this is because many issues are reported in this area (as for others as well).

Anyway, the simpler solution is in this pull: https://github.com/robertoDiaz/liferay-portal/pull/609

Best regards,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

@moltam89 reviewed the simpler solution and raised concerns about it, because it seems that it resolves the issue only partially.
It turned out that when importing a .lar file, `_detector.detect `is called twice, once from the `ImportLayoutsMVCActionCommand` class (where I set "application/zip" to be the mime type) but also once when the file size validation was running.
If a file's mime type detection takes 10 minutes time, after the fix it still would take 5 minutes time.

I decided to return to the solution that operates closer to the code piece which is behaving in an undesirable way - namely `_detector.detect` which runs slowly, but with including improvements and some simplification.
This time, I introduced a separate extensions map, `_customExtensionsMap`, which is independent of the original `_extensionsMap`.
`_customExtensionsMap` contains only the extension mapping that is defined in _tika/custom-mimetypes.xml_.
`MimeTypesImpl.getContentType(InputStream inputStream, String fileName)` will first look in `_customExtensionsMap` and if it doesn't finds anything will proceed with the usual detection mechanism.
In addition, this version of the solution doesn't break the tests, since it depends wholly on the custom extensions.

Please let me know what you think.

Thank you!
István

**Pull request closed without merging**
