### PR TITLE
LPS-69171

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-69171

Hey Roberto,

I've made changes based off our forum posts here: https://in.liferay.com/web/support/forums/-/message_boards/view_message/26401197#_19_message_26401197

I've tested with public/private layouts, layoutSets, and orgs and have found them all to work as intended (public will show image normally, private will redirect to login page).  Let me know what you think.

-Chris

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/4313. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
