### PR TITLE
LPS-81743 FileSystemStore > S3Store migration won't migrate previews and thumbnails

### PR DESCRIPTION
**Pull request by hudakl**
Hi Roberto,

Your suggestion resolved the migration issue. I only needed to add a small change.
Could you please review the changes?

Thank you,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @hudakl 

Why do we need to do the replace in this case??

Did you check with different stores (fileSystem to AdvancedFileSystem, for example) or just from X to S3??

**Comment by hudakl** [comment]
The replace was necessary because otherwise it added an additional folder called '/' to the tree, because the _sourceStore.getFileNames method returned with paths like this:
document_preview//20142/220/36572/36573/

I haven't tested yet with other migration processes, but I reckon that extra character would break them too.

**Comment by robertoDiaz** [comment]
I see. In fact in other parts of the portal we are doing something similar. See AMThumbnailsOSGiCommands:86.

Can you modify your logic to match this one and resend??

`String actualFileName = StringUtil.replace(fileName, "//", StringPool.SLASH);
`
Thanks!!

**Comment by robertoDiaz** [comment]
Hey @hudakl 

I'm going to send the code, so do not resend it.

Thanks!!

**Comment by robertoDiaz** [comment]
@hudakl 

See https://github.com/adolfopa/liferay-portal/pull/685.

I've also included more elements.

**Pull request closed without merging**
