### PR TITLE
LPS-73946 When a user has many connections and the Microblogs portlet is added to a page, rendering it takes a lot of time

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertodiaz

referring to #591, I have find a solution for the net::ERR_CONTENT_DECODING_FAILED error by disabling GZIP filtering only for that one request.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
hey @IstvanD 

Can you check if the broken test are related with the pull. I guess they are not, but could you assert that?

Thanks!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3972. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/60303ef52156~1...60303ef52156) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/619. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/60303ef52156~1...60303ef52156) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I've finally discard the last change, since the autocomplete seems to work without it.

I've also add a small SF

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Sorry for the late answer.
I've checked the failed test, but they don't seem to me to be related either.

**Pull request closed without merging**
