### PR TITLE
LPS-76191 Switching off email notifications on comments is also blocking web notifications

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I rebased the changes that you made in https://github.com/IstvanD/liferay-portal/pull/51

It's not all thze same though as the logic in SubscriptionMBMessageLocalServiceWrapper has been moved back to MBMessageLocalServiceImpl.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hi. 

I'll review that on Monday.

Anyway, I think that testAddUserNotificationWhenEmailNotificationsDisabled() and testUpdateUserNotificationWhenEmailNotificationsDisabled() are not the same case as the described in this ticket. I mean, this test are checking what happens if the notifications are disabled using the UserNotification API, not the DISCUSSION_EMAIL_COMMENTS_ADDED_ENABLED property.

I need to confirm this.

Thanks!!

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4282. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/420f2d256693~2...420f2d256693) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
