### PR TITLE
[Technical Support] LPS-66216

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-66216

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/jorgediaz-lr/liferay-portal/pull/64. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/ced4ac7~1...ced4ac7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
