### PR TITLE
[TS] LPS-109784 Enable auto login for /c/document_library/get_file/* path

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-109784](https://issues.liferay.com/browse/LPS-109784)

Hi Roberto,

I am sending the changes as discussed on the PTR ticket earlier. 

Please let me know if I can be of any help.

Thank you for reviewing. 

Best regards,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1335.

**Pull request closed without merging**
