### PR TITLE
LPS-117473 Check the required vocabularies at the global site level too | TS

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @robertoDiaz

the Vocabulary created at Global site level was not checked for requirement for Document upload.

Could you please check my fix?

Similato to this one: https://github.com/robertoDiaz/liferay-portal/pull/834

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @robertoDiaz 

could you please review this PR and push it forward?

Thanks, Roland

**Comment by robertoDiaz** [comment]
Hi @rolandpakai 

We have a peak of tickets in Spain.

I'll push this to the team once I have bandwith to do so.

To could provide this as SDH to the customer if needed.

**Comment by rolandpakai** [comment]
Hi @robertoDiaz

could you please review this PR and push it forward?

Thanks, Roland

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/rolandpakai/liferay-portal/pull/21. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/600ad2b4dd0c~1...600ad2b4dd0c)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/514. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/600ad2b4dd0c~1...600ad2b4dd0c)

**Pull request closed without merging**
