### PR TITLE
LPS-86455

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @robertoDiaz,

Thanks for looking at this issue. I've verified that this fix also works for images and audio files. The only changes I have made is to rebase it to latest master and to run source formatter. Please let me know if there's anything else I can do for you to help with the testing of this issue. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/785. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/e214b5ecdd1f~4...e214b5ecdd1f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
