### PR TITLE
LPS-55103 Consistency with LiferayFolder and LiferayFileEntry

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Clean up FileShortcut interface. It shouldn't have any reference to trash (as FileEntry or FileShortcut) and we shouldn't have a method getStatus() since it seems that it's only used by trash (which won't be supported as it is right now by 3rd party repositories. 

Make sure that the implementations of everything related to FileShortcut matches FileEntry or Folder to make it all consistent.

Thanks!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/219. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2146. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
