### PR TITLE
master-qa-22585

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-22585

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @robertoDiaz, these commits should fix tests failing from LPS-63508. Would you mind rebasing and sending it to @sharonchoi?

@sergiogonzalez

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2958. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2961. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/6fbf037~2...6fbf037) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2962. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/48f1238~2...48f1238) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2963. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/abe2d5b~2...abe2d5b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2965. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/2c9f2064~2...2c9f2064) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
