### PR TITLE
LPS-98654 Using System Configuration to find the correct AM Configuration

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @robertoDiaz 

I have implemented a version that utilizes the Configuration framework for finding the AM thumbnail resolution.

There is a small problem left: the configuration is not read properly, thus the entry values cannot be accessed. `amThumbnailConfigurationId` will always be a black string

Do you have an idea of what I might be missing?

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
I think that you should create the ConfigurationBeanDeclaration for this configuration.

Does it make the trick??

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Many thanks, your suggestion helped.
It is now working as expected.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I have updated this pull with adding AMThumbnailConfigurationBeanDeclaration.

Best regards,
István

**Comment by robertoDiaz** [comment]
@IstvanD thank you.

I'm going to review this today

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/86. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/87ecb6f0b0c4~1...87ecb6f0b0c4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
