### PR TITLE
[TS] LPS-121370

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello @robertoDiaz,

This is based on the discussion from https://issues.liferay.com/browse/PTR-1959.

There is an issue in Master currently when rendering the edit document page. I temporarily worked around it by removing the following lines - https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/com/liferay/dynamic/data/mapping/service/dependencies/init.ftl#L175-L181

Please let me know if you have any questions about the changes or see any possible issues.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/831. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/d29f1f3d3448~1...d29f1f3d3448)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/832. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/53ad18b4813c~1...53ad18b4813c)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/854. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/ed1ffb388e41~5...ed1ffb388e41)

**Pull request closed without merging**
