### PR TITLE
LPS-61966 Use `sidepanel` tag to make info pane reflect changes

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/192. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/dab6808~3...dab6808) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34469. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/dab6808~3...dab6808) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
