### PR TITLE
LPS-83963 Small Image not available while editing blog entry after upgrade to DXP

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I implemented the first 3 points of your suggestions in https://github.com/robertoDiaz/liferay-portal/pull/714#issuecomment-412831666 (as separate commits).

I'm not sure however, that 4 (using the API of Blogs local service) could be applied here.
addAttachmentFileEntry would add an attachment to the Blogs entry, not a small image. The latter is not implemented as an attachment of a Blogs entry.
Turning public and using addSmallImageFileEntry would not work because the method expects an ImageSelector, which has to be properly initialized. Adding small images are done by employing the Image Selector, but in our case, in the upgrade process, we cannot use that.

When designing the upgrade process I took multiple APIs into consideration, but found that only PortletFileRepositoryUtil has an API where all the the data that is available in the upgrade environment can be passed to it's method.
Also PortletFileRepositoryUtil is used by addSmallImageFileEntry.

Please let me know what you think.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

I've been reviewing the code and after a small chat with the PT they told me that this Upgrade Process should not be necessary.

The old ImageLocalService API should work in blogs, and the images are updated to the new API in a lazy way (when the blogs entry is updated the image should be converted to a file entry). This is why we didn't made the upgrade process while developing this.

Taking this into account, could you reevaluate the fix and check why this approach is not working??

Another think is that they ask me to introduce tests if we do any change to this.

If you need help, feel free to open a SME request in order to track this task.

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

The edit entry view employs the `liferay-item-selector:image-selector` taglib for displaying it's existing Small Image (in case there exists one) and selecting a new Small Image.
The code that deals with this is in _modules/apps/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/image_selector/page.jsp_
It will fetch the image from the Document Library via `DLAppLocalServiceUtil.getFileEntry`, but Small Images created in 6.2 are not part of DL, and they have no entry in the `dlfileentry` and `dlfileversion` tables.
Consequently, the Image Selector will not be able to display those images.

In theory, we could modify Image Selector so that is searches for the image with the ImageLocalService API when the image is not found by `DLAppLocalServiceUtil.getFileEntry`.
However, another problem will still exist: if the user clicks on that image, the opening Item Selector portlet  will not show the image among the Blog Images, thus it won't be able to be selected again in the case the user selects/uploads another Small Image.
The reason on this is because, on DXP, when uploading an image, two DL File Entries will be created:

1. a scaled down image file that will be displayed in the blog's abstract
2. an image that will be created in the blog images repository. This image is selectable from the Item Selector if the user wanted to select another image that was previously uploaded.

This is the reason the upgrade process created two DL File Entries for each small image. The image will be displayed by the image selector AND the image will be able to be chosen from the item selector.

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

I see, I had another conversation with the PT and we agreed in check the upgrade (since it's the only solution that covers all the cases). 

Anyway, since it is too risky, and the customer has fix it's situation, and the workaround is as easy as save the blogs entry (and regenerate the image as file entry) the most probable resolution for this LPS is a won't-fix.

Thanks, and nice job 👍

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/sergiogonzalez/liferay-portal/pull/4553. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
