### PR TITLE
LPS-86575 Wiki: Identical header titles will lead to identical links in table of contents

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

It is possible to create table of contents that have identical titles.
For example, there may be more than one heading named Heading1, which will lead to multiple entries in the table of contents with the title Heading1.

If this happens, all of the entries with the title Heading1 will link to the first Heading1 header in the Wiki page, although each Heading1 titled entry should point to it's respective heading.

I solved this issue by keeping track of ToC entries and headings each in their own Maps, and generate unique serial numbers for their occurrences if they happen to appear more then once in the Wiki page.

Thank you,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/74. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/4494374f91f0~1...4494374f91f0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
