### PR TITLE
LPS-78083 Wiki-Details-History-Versions shows the same date of creation for all versions

### PR DESCRIPTION
**Pull request by hudakl**
Hi Roberto,

Could you please review @laszlopap 's solution proposal.

Thank you,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @hudakl  and @laszlopap:

I can see the change of the method call (createDate to statusDate), but why are you changing the way it is formatted??

It doesn't seem to be problematic.

**Comment by laszlopap** [comment]
Hi @robertoDiaz ,

It is used because we want to display the "age" of the version. For example: '20 minutes', or '3 days'.

Regards,
László

**Comment by robertoDiaz** [comment]
Yes, but this is a behaviour change that is not related with the fix. 

I mean, we could fix the error without it. This view, with the current behaviuor was designed by UX team and we should not change it without an agreement with them.

Please resend without it and create a new feature request to so they could analyze if we should change it.

Thanks.

**Comment by laszlopap** [comment]
Hi @robertoDiaz ,

I have attached a screenshot about the expected behaviour to the LPS ticket.

Please check it, and consider checking this solution after that.

Thanks,
László

**Comment by robertoDiaz** [comment]
Hi @laszlopap 

By the moment, the expected behavior is to use the current format.We should not handle behavior changes.

So please, resend with the minimum fix and If you think that we should change the format of the date, please create a new feature request or create a PSM about this.

Thanks!

**Comment by laszlopap** [comment]
Hi @robertoDiaz ,

The behavior wasn't changed. In that column always the age of the page was displayed, but for every version the first version's age was shown. In the fix this formatting needed to be introduced, because when the difference was added to the row a date appeared.

Please consider this, when reviewing the changes.

Regards,
László

**Comment by robertoDiaz** [comment]
So, why couldn't you do:

`row.addDate(curWikiPage.getStatusDate(), rowURL);`

instead of

```
Date currDate = new Date();
Date modifiedDate = curWikiPage.getStatusDate();

String dataAsText = LanguageUtil.getTimeDescription(request, currDate.getTime() -modifiedDate.getTime(), true);

row.addText(dataAsText, rowURL);
```

**Comment by laszlopap** [comment]
The solution would be good in some cases, but here I need to display the time difference (the 'age' of the version), not the proper date, when it was last edited. 
It is similar to the data displayed on the activities tab.

**Comment by robertoDiaz** [comment]
So, there is a behavior change???

**Comment by robertoDiaz** [comment]
@laszlopap, about:


> I have attached a screenshot about the expected behaviour to the LPS ticket.
> 
> Please check it, and consider checking this solution after that.


I've just check the image and doesn't looks as an acceptable behavior.

The original column value shows  the  "X-ago" pattern, for example " a week ago", "30 seconds ago" etc. But with your change, the message looks like "17 seconds", "5 minutes", "16 hours" which doesn't make sense to me.

The row.addDate method handles this. To see it check the DateSearchEntry.java class. 

And by the way, it seems that we should call curWikiPage.getModifiedDate() as we do in other parts of the product.

We should also fix this issue in wiki_admin/page_info_panel.jsp:233, since we are using the createDate instead of modifiedDate.

Please resend with all this changes.

**Pull request closed without merging**
