### PR TITLE
[TECH SUPPORT] LPS-72612 Moving (renaming) a Wiki page removes all categories and tags

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this PR:
https://issues.liferay.com/browse/LPS-72612
dsanz#68

Thanks!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @rimisaadouwork,

I've check the test and it doesn't reflect the ticket description use case. See:

> 1) Patch Vanilla DXP with de-12-7010 and start it, login as Admin
> 2) Create 2 categories and 2 tags in the Site Administration section for the default site
> 3) Place a Wiki porlet onto the Welcome page
> 4) Edit the Front Page, enter any text in the body, categorize the Wiki with the 2 tags and categories created at step 2). Publish.
> 5) Click on Details > "Details" tab > Bottom part: "Move" > New Title, give any new title and Save. Operation will complete successfully, the Wiki page will have a new title

If I'm not missing something what the test is doing is:

> 1) Patch Vanilla DXP with de-12-7010 and start it, login as Admin
> 2) Create 2 categories and 2 tags in the Site Administration section for the default site
> 3) Place a Wiki porlet onto the Welcome page
> 4) Edit the Front Page, enter any text in the body, Publish.
> 5) Click on Details > "Details" tab > Bottom part: "Move" > New Title,  give any new title and 2 tags  and Save. Operation will complete successfully, the Wiki page will have a new title

(See steps 4 and 5 in detail in both cases)

In fact I guess that the test is not reflecting any UI interface use case (since it is not possible to tag or categorize while renaming)

Did I miss anything??

Thanks!

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by rimisaadouwork** [comment]
Hi @robertoDiaz ,

Correct me if I am wrong. 
The test is Adding AssetTagNames to the serviceContext. When you press the move button in UI this will also happens. Then we call WikiPageLocalServiceUtil.renamePage this will do the same as move. In the background a new wikipage and assetEntry will be created. The last step is getting the assettagenames of the renamed(moved) page and compare them to the created one.

So we are testing if the asset tags are moved to the new wikipage.

Thanks!

**Comment by robertoDiaz** [comment]
The test (following the description) should be adding the asset tags (and categories) when adding the wiki page and assert that this tags and categories are been populated when moving. This is the use case described in the description.

I've check the move_page.jspf and the rename_page.jspf and I didn't found this fields in the form, so 
I'm going to check how this is been populated when moving the pages, because this is confusing me.

I'll tell you ASAP

Thanks

**Comment by robertoDiaz** [comment]
It seems that the tagnames and the categories are been populated in the "com.liferay.wiki.service.impl.WikiPageLocalServiceImpl#populateServiceContext" method, as said before, the test should be made like this:

> The test (following the description) should be adding the asset tags (and categories) when adding the wiki page and assert that this tags and categories are been populated when moving. This is the use case described in the description.

It is not necessary to add the tagnames when moving, because the wiki service logic is populating the service context with it.

Thanks!

**Comment by robertoDiaz** [comment]
@rimisaadouwork,

I'm creating the tests.

I'll mention you once I've move this to @adolfopa

Thanks!

**Comment by rimisaadouwork** [comment]
Hi @robertoDiaz ,
Thanks for creating the test. You are helping me a lot with that because I'm dealing now with other issue with higher priority.
Thanks!

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/556. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/1b4f7b0b31c3~3...1b4f7b0b31c3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
