### PR TITLE
LPS-85733 Link to documents in Wiki (MediaWiki type) are not correctly updated after > Liferay Wiki import page

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I eventually kept `translateMediaLinks()` in the `MediaWikiImporter`, because the conversion, and therefore, testing the conversion relies on the page being imported.
`MediaWikiToCreoleTranslatorTest` doesn't assumes that a page is imported (it's not even aware of any page), and also don't assumes the "SharedImages" page existing along with it's attachments.

So I added a new test case to `WikiNodeLocalServiceTest`, that imports a page with it's related files, which is able to fetch the attachment from "SharedImages", create an attachment URL, and compare it to the one created in the Wiki Page.

Can we go with this approach?

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

Sorry for the delay. 

I'm going to review and pass this PR today.

Regards!

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/714. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Sure. Thank you for forwarding it.

Regards,
István

**Pull request closed without merging**
