### PR TITLE
LPS-75749 Notification event can be deleted before invitation is accepted or declined

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check if this solution is correct?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@IstvanD 

Can you check if the test error are been produced by the changes??

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have checked the failed/unstable tests one by one.
They are not related to the solution.

Best regards,
István

**Comment by robertoDiaz** [comment]
@IstvanD 

Ok, I'll try to review this afternoon or tomorrow morning

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/49. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/b9ac5237fc50~1...b9ac5237fc50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
