### PR TITLE
LPS-98654 SF and mocking AMSystemImagesConfiguration in test

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I have made some corrections, SF and mocked AMSystemImagesConfiguration as you recommended.

I'm now sending the pull and watch if any tests fail.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

The PrefsPropsUtil.getInteger(... test failures appeared ci:test:relevant

**Comment by robertoDiaz** [comment]
Yes, I've seen it.

I'll fix it an move the PR forward  during this week

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/317. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/5b94e8bc6b74~2...5b94e8bc6b74) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1065. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/5d60e47de844~2...5d60e47de844) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
