### PR TITLE
LPS-74412 Limit the embedding of the subsequent messages for the sake of readability

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

It is forwarded from https://github.com/IstvanD/liferay-portal/pull/40

Thank you,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/41. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/4a7775d1ea96~2...4a7775d1ea96) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

According to the message in the original pull https://github.com/IstvanD/liferay-portal/pull/40#issue-254017065

> With limiting the depth to 4 I followed the pattern in the /apps/collaboration/comment/comment-taglib/src/main/resources/META-INF/resources/discussion/view_message_thread.jsp

I am wondering if we could use the same strategy here.

Please let me know what you think.

Bests,
István

**Comment by robertoDiaz** [comment]
Hi @IstvanD and @hudakl 

I've agreed with @sergiogonzalez that is better to use the css approach since it has some benefits (

- donot hardcode the depth in the jsp

- allow developers change the message style and use a different depth if they want by changing the theme css

Saying this, of course, the solution should be consistent in all the places, so could you apply it to discussion/view_message_thread.jsp too?

If you need some help, please tell me.

**Pull request closed without merging**
