### PR TITLE
LPS-68095 Users cannot add announcements on their own dashboard

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull?

I'm not sure whom to assign it because the issue borders Collaboration and Security.

It is reproducible only on ee-6.2.x because the permission check at the the beginning of the AnnouncementsEntryServiceImpl.addEntry() was removed by [LPS-67115](https://issues.liferay.com/browse/LPS-67115)

Observations by @topolik:
https://github.com/topolik/liferay-portal/pull/373#issuecomment-251138971

@sergiogonzalez your thoughts are also welcome.

Thanks!

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
This should not be merged in master.

I think you did send it to the wrong branch, maybe 7.0.x or 6.2.x??

Can you resend?

**Comment by IstvanD** [comment]
It was meant for backporting once it's merged to master.

OK, I'll send it to ee-6.2.x.

**Comment by robertoDiaz** [comment]
Yeah, but since in master this is not useful, it should not be merged there. (or at least 'this aproach')

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I see.
I'v sent you a pull for ee-6.2.x: https://github.com/robertoDiaz/liferay-portal-ee/pull/9

**Pull request closed without merging**
