### PR TITLE
LPS-55859

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same pull than https://github.com/robertoDiaz/liferay-portal/pull/248 but modified because of last developments at master (LPS-53821 and others)

This LPS was commited to master at brianchandotcom#26831 but I forgot to send this commit jorgediaz-lr@ab7d3cf

Thank you

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @robertoDiaz 

Can you have a look to this pull?

Thank you

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
rebase to last master version

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebase to last master version :eyes::eyes::eyes:
:hand::hand::hand:

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
solved a SF error

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Closing due it seems that further changes in Item Selector will solve it.

Please retest once LPS-56842 is merged

**Pull request closed without merging**
