### PR TITLE
[TECHNICAL-SUPPORT] LPS-113120 Image Editor changes are not applied if the title of the image is missing the extension

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-113120](https://issues.liferay.com/browse/LPS-113120),
Please find the workaround for testing on the LPS
Please review my changes.

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
blocker - https://github.com/robertoDiaz/liferay-portal/pull/829

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/124.

**Pull request closed without merging**
