### PR TITLE
LPS-81373 Consecutive '<' characters aren't rendered properly

### PR DESCRIPTION
**Pull request by IstvanD**
hey @robertoDiaz 

Could you please check this pull request?
I added a symbol to the Creole parser rules to treat '<<' as a distinguished character sequence.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

It's highly probable that the PT, in order to merge this in master, will ask for unit test for this.

Are you able to add one test??

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I added a test case.
1ecb13b7cf95dd59ab48ee72c0a073aee615d979

Do you think this will suffice?

Thank you!

Best regards,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4444. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
