### PR TITLE
LPS-68590 Mentions autocomplete can't handle all valid characters in screenNames

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

This fixes the issue of the autocomplete used in user mentions not being triggered for special characters in user names.

Thank you!

Bests,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

I've been looking the code with @adolfopa, and we do not understand what does the "trigger" literal meaning of this regexp.

Can you explain this to us??

Thanks!!!

**Comment by IstvanD** [comment]
The trigger is the placeholder for the character which will indicate that a user is mentioned.
It will be '@' character by default.

For example if I start to type @ and the username, the autocomplete will pop-up, eg. triggered, just like here in the GitHub comment editor.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I was wondering what you think about the solution.
Does it makes sense technically?

Thanks,
István

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/359. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
