### PR TITLE
LPS-117368 | TS

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @robertoDiaz 

the Vocabulary created at Global site level was not checked for requirement for Document upload.
I created the hasRequiredVocabularies method for checking the assetVocabularies and the companyAssetVocabularies.

Could you please check my fix?

Thanks, Roland

https://issues.liferay.com/browse/LPS-117368

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:stop

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @robertoDiaz 

could you please review this PR and push it forward?

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @robertoDiaz

could you please review this PR and push it forward?

Thanks, Roland

**Comment by robertoDiaz** [comment]
Please see https://github.com/rolandpakai/liferay-portal/pull/21

**Pull request closed without merging**
