### PR TITLE
LPS-124848

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

As requested, I'm sending the pull request back.

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Hi,

I'm waiting for an additional pr to merge them in a unique one and push all to master.

If you wish you could provide an SDH to the customer based in this solution (maybe you have to add changes related with the first upgrade)

**Comment by IstvanD** [comment]
Hi,

OK, I have created and released the SDH.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I'm wishing you a happy new year!

The SDH has been created and released to the customer.
If there is any news about the status of the merging of the additional or, please let me know.

Thank you,
István

**Comment by robertoDiaz** [comment]
not yet.

I'm working in it.

Hopefully the next week I'll have a final solution for this.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Got it. Thanks for the reply.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Is there any news about the pr?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Not yet, 

I'm waiting the other pull to be merged

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Rebase error. :(

Can you check and resolve this errors??

Thank you in advance.

**Pull request closed without merging**
