### PR TITLE
LPS-139816

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-139816

Hello @robertoDiaz,
I have fixed the source formatting issues (from the discussion in this [PR](https://github.com/robertoDiaz/liferay-portal/pull/876)). However, I am still getting the NPE at startup and I even asked a colleague to test it and they are able to see the error as well.

Please let me know what the next step is. Should we arrange a screenshare so I can show you the error on my end if you cannot reproduce it?

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Pull request closed without merging**
