### PR TITLE
LPS-80082 "Recent changes" of Wiki portlet is not sorting based upon recent changes

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I added the baseline changes that were missing in https://github.com/robertoDiaz/liferay-portal/pull/673

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/62. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/328f867b9877~2...328f867b9877) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/63. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/54c85e1f9a68~2...54c85e1f9a68) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
