### PR TITLE
Lps 139816

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-139816

Hello @robertoDiaz,
I have adjusted the fix as you suggested and the behavior works as expected now. 

However, I have noticed that a change made by LPS-143165 has changed the current behavior than what is described in LPS-139816. Before these changes, when a new page "test" is created while "/test" is an old FURL for another page, then the page cannot be created. The expected behavior is that the page is created with a FURL of "/test1". The current behavior shows that the page will be created successfully but the page's FURL will be "/test-1".

In this case, the fix now is only fixing how the page is being incremented. I still believe that this fix is necessary because there are two different behaviors when adding a new page with a duplicate FURL. If the duplicated FURL is a currently used one, then the name will be incremented by "i" but if the FURL is an old one, then it's incremented by "-i". Therefore, this fix will make both scenarios increment the name by "i".

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
So, If I understand it well the current bug is that the generated FURL is different depending on the use case. Is it right?

**Comment by noornajj** [comment]
Yes, that it correct

**Comment by robertoDiaz** [comment]
Hey @noornajj, 

It seems that there's a conflict

Could you update the LPS description (to the current behavior) and resend to the lima team??

Thanks!!

**Pull request closed without merging**
