### PR TITLE
LPS-122226

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-122226

As discussed and created through PTR-2010. Creating this PR for CI testing purposes. 

Sincerely,
Brian

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hey @brianikim 

Can you check if the failures are related with your changes??

Thanks!

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @robertoDiaz, failures were not related to this changes, now tests are green, so please procceed with the pull. 
Thanks! 

/cc @brianikim

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/905.

**Pull request closed without merging**
