### PR TITLE
LPS-84043: SF

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
ci:test:sf

**Comment by renatodepaiva** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/renatodepaiva/liferay-portal/pull/15. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/4d62665e40e9~1...4d62665e40e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4550. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/44d932577486~1...44d932577486) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
