### PR TITLE
master-sc-392

### PR DESCRIPTION
**Pull request by sharonchoi**
@robertoDiaz these are the test fixes for your pull here:
https://github.com/sharonchoi/liferay-portal/pull/392

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@robertoDiaz taking at look at the failures now

**Comment by sharonchoi** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35043. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/35087

**Pull request closed without merging**
