### PR TITLE
LPS-85419 Web content comments subscriber recevices an email after up date of the web content

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

There was a minor formatting error in https://github.com/robertoDiaz/liferay-portal/pull/731 causing that pull request to closed.
I have resolved the error and thus resending the pull request.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Are this broken tests related with your changes??

Thanks!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

They don't seem to be related.

Best regards,
István

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/72. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/58bfbb465be5~1...58bfbb465be5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
