### PR TITLE
LPS-73946 When a user has many connections and the Microblogs portlet is added to a page, rendering it takes a lot of time

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I implemented the solution with utilizes resource URL.
It's indeed slimmer by multiple factors.

Could you please review it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@IstvanD 

Looks better! :)

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

I've seen that the new logic works as expected.

Anyway, I can't see where is that list introduced in the markup. I think that this should be included in the "highlighterContent" div, but it seems to be empty. Can you clarify this?

Thanks!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Do you mean the responseData array that gets assigned to A.AutoComplete's source parameter?

`source: responseData`

It is the return argument the success callback function receives.

`success: function(responseData) {`

**Comment by robertoDiaz** [comment]
Yes, I see that, but I haven't seen how is that list used.

AFAIK this function should use this response data to autocomplete the highlighterContent div, but it seems to be empty in the resulting markup.

**Comment by IstvanD** [comment]
I haven't yet observed the generated markup.
However, I tested by typing the name of the connected users, and the autocomplete seems to work.

**Comment by IstvanD** [comment]
I am now testing the hotfix, but there are problems.
The autocomplete is not working when the minifier is turned on.

Probably is this because of the missing markup?

I checked GetJSONRecipientsMVCResourceCommand, it get's called and it return the result array.

Thank you!

István

**Comment by robertoDiaz** [comment]
Yes, that's exaclty what I've found,

the actions is been called and works as expected but the js is not (or at least doesn't autocomplete in some cases)

Could you handle this, since it seems to be failing (or at least create a new LPS with this "bug"). 

Once we have fix or report this situation we could move forward and pass the current pr.

Thanks in advance.

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

There is something with content encoding.
If I set `com.liferay.portal.servlet.filters.gzip.GZipFilter=false` the jsonArray returns correctly and the results are shown.

**Comment by robertoDiaz** [comment]
Can you test if this is a problem as a result of the pr changes or if this is an error that happens in current master?

Thanks!

**Comment by IstvanD** [comment]
I that trouble to test this issue with other resource URLs, but I found that this may be an issue on other systems too
https://stackoverflow.com/questions/41253130/ajax-php-neterr-content-decoding-failed

**Comment by robertoDiaz** [comment]
I mean, If you could test it in microblogs, in current master, and if the js if failing depending on the GZip filter configuration? (just the same use case but without this changes produces the same behaviour - an empty div)

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I'll test this also on master, however, I have found a solution that I applied to the hotfix and released it to the customer.

**Comment by IstvanD** [comment]
I'm closing this pull and will resend it with the solution.

**Comment by robertoDiaz** [comment]
Ok.

Thanks!

**Pull request closed without merging**
