### PR TITLE
LPS-85732 Categories Navigation portlet leads Documents and Media portlet in "Descriptive" style to break

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?
I used a similar solution that was used for Bookmarks in LPS-60833
https://github.com/liferay/liferay-portal/blob/master/modules/apps/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/view_entry_descriptive.jsp#L26

Thanks!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4606. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/d652106cb7c3~1...d652106cb7c3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4610. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/dd0418587afb~1...dd0418587afb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
