### PR TITLE
[TS] LPS-126145

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @robertoDiaz,

This solution tries to solve the case for the JournalArticle by checking by TYPE_LATEST in addition to TYPE_LATEST_APPROVED.

Could you please review it? Please, let me know if you have any concerns about this fix.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
hey @laszlopap 

Can you check if the broken tests are related with your changes?

**Comment by dacousalr** [comment]
Some tests seems to have been aborted. Re-running...

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
Hi @robertoDiaz,

Could you review this?

Thank you!

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/laszlopap/liferay-portal/pull/16. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/1b8c48b5714b~4...1b8c48b5714b)

**Pull request closed without merging**
