### PR TITLE
LPS-69997

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @robertoDiaz,

Attached is an update for http://issues.liferay.com/browse/LPS-69997.  It seems like that ftl file has a bunch of other issues too which might need to be addressed.

Attached is a screenshot of the page:
template
 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3765. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @jonmak08 

I've found more cases of .ftl using liferay_ui["discussion"]

Did you detect this cases?

Please see:

- com/liferay/portalweb/dependencies/adt_wiki_social.ftl:176

- com/liferay/asset/publisher/web/portlet/template/dependencies/portlet_display_template_rich_summary.ftl:77

- com/liferay/portalweb/dependencies/adt_asset_publisher_rich_summary.ftl:77


Could you include this change in this places if needed, test it and resend??

Thanks!!!!

**Comment by robertoDiaz** [comment]
I've seen that you send a bunch of pr related with this.

If you have already sent the commented cases, of if they do not need to be changed in this pe, tell me, or resend this directly to sergiogonzalez.

Thanks!!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/sergiogonzalez/liferay-portal/pull/3769

**Pull request closed without merging**
