### PR TITLE
LPS-82009 Add Adaptive Media configuration for image previews

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I discovered that image thumbnails are generated by Adaptive Media, while image previews are still created the old way.
Now, that AM deals with rotation of images with Exif orientation metadata, the thumbnails are displayed in the correct orientation. This is not the case with previews.
The Thumbnail AM configuration is added automatically whenever a new portal instance is created.

I thought about adding a similar default AM configuration for previews.
According to my tests, if the image the preview is generated for contains Exif orientation data, the newly added Preview AM configuration correctly rotates the image.

This solves the issue of [LPS-76893](https://issues.liferay.com/browse/LPS-76893), but I opened the separate LPS for this, as this is may solve more issues, for example when the preview is viewed in Documents and Media (the preview orientation is wrong there too).

I added the new code in **adaptive-media-document-library-thumbnails** module, but if you think that the additions should be added to new module, like **adaptive-media-document-library-previews**, please let me know.

Thank you if you review the changes!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/sergiogonzalez/liferay-portal/pull/4473. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/5c1e1609940e~4...5c1e1609940e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Thanks for forwarding it!

**Comment by robertoDiaz** [comment]
👍 @IstvanD 

Yes, I've been talking with @sergiogonzalez explaining him the case, and he wanted to review it.

I've also change the ticket type from bug to regression since it was fixed in 7.0.x.

**Pull request closed without merging**
