### PR TITLE
LPS-75749 Notification event can be deleted before invitation is accepted or declined

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I added the `userNotificationFeedEntry` as a `rowData` for the seach container.
Each `search-container-column` in a `search-container-row` will see the same `userNotificationFeedEntry`.

Best regards.
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@IstvanD 

Can you confirm that the broken test are not related with this pr??

Thanks!!

**Comment by robertoDiaz** [comment]
@IstvanD 

Any update on the broken test check?? Could I push it to master?

**Comment by IstvanD** [comment]
@robertoDiaz 

I'm sorry for the late reply.
It's a source format error. I'll fix it, and resend the pull.

Best regards,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have corrected the SF errors
https://github.com/robertoDiaz/liferay-portal/pull/622

**Pull request closed without merging**
