### PR TITLE
LPS-69917 Format the average score in page.jsp according the javascript

### PR DESCRIPTION
**Pull request by cleydyr**
/cc @rodrigopaulino
Relevant issue: https://issues.liferay.com/browse/LPS-69917

Forwarded from https://github.com/dsanz/liferay-portal/pull/63

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @rodrigopaulino, @cleydyr 

I'm review this and I do not understand why did it fail.

If we format the average when adding (in the action) as we do in current master, I do not understand how non formatted value could be shown in the view.

I'm going to check it a little deeper, so please, be patient with this.

Thank you guys!

**Comment by rodrigopaulino** [comment]
Great, @robertoDiaz.
If you need anything, just let me know.

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3855. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
