### PR TITLE
LPS-68897 Conversion without Guest permission does not include images when the url contains &imageThumbnail=1

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?
This adds a small modification to the document link regex patterns to be able to match with URLs that have additional parameters.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
@IstvanD, 

Can you explain a little bit about the problem and the changes you made to fix it??

Thanks!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Sure.
The patterns are matching URLs that can point to images.
Because ampersands (&) were not allowed, and URL query parameters are delimited by ampersands. the URLs could not have more than one query parameter.

Best regards,
István

**Comment by robertoDiaz** [comment]
Got it!

Thanks!

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/sergiogonzalez/liferay-portal/pull/4108. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/6dd4ca55918e~1...6dd4ca55918e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
