### PR TITLE
LPS-80700 SQLServerException thrown when adding a KB article inside a KB folder, with MS SQL Server

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

The `com.liferay.knowledge.base.service.persistence.KBArticleFinder.countByUrlTitle` query in _modules/apps/knowledge-base/knowledge-base-service/src/main/resources/META-INF/custom-sql/default.xml_  contains the clause count(*) which will lead the line

```
...
query.addScalar(COUNT_COLUMN_NAME, Type.LONG);
...
```

in `KBArticleFinderImpl` to fail.

Thank you,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/680. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/157dd29b649e~4...157dd29b649e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @IstvanD,

The code is ok. As far as I've seen this problem is reproducible when using MS SQL Server database.

I think that if we had had an integration test we have check this query it in all the DB supported by the CI, so, are you able to create this tests and resend?

In order to do that we could check KBArticleLocalServiceImpl#getUniqueUrlTitle(long, long, long, java.lang.String) in the KBArticleLocalServiceTest class.

I would appreciate it. 

Thanks!!

**Comment by IstvanD** [comment]
hey @robertoDiaz 

Sure, I can add the tests. But as I see, KBArticleLocalServiceImpl#getUniqueUrlTitle(long, long, long, java.lang.String) is not a public method. I figure it then cannot be used in the tests, or can it?

Thank you,
István

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I've just check that we do not have specific integration test for SQL Server :(

So, it is probable, that following we are hitting this logic, but we have not detect this case.

I'm going to move it forward to @adolfopa 

Thanks!!

**Comment by IstvanD** [comment]
As I see, KBArticleLocalServiceImpl.addKBArticle() calls this logic, but now I'm testing if it is called somewhere in the tests.

**Pull request closed without merging**
