### PR TITLE
LPS-74747 Animated gifs should appear animated in Blog headers

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

This is a follow-up of this pull:
https://github.com/robertoDiaz/liferay-portal/pull/614

Changes to the original pull:
- As discussed I moved the logic to the ImageSelectorProcessor
- I ommited the getDelay method as it turned out to be unnecessary
- I ommited the last commit of the previous pull, since the error it supposed to handle occurs without a fix as well

Is the fix OK like this?

Thanks,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @hudakl 

I think that this has been solved in master in this LPS : https://issues.liferay.com/browse/LPS-75840

Can you test it??

If it works it will be fixed for DXP too since this is going to be released as part of Adaptive Media release.

**Comment by hudakl** [comment]
Hi Roberto,

It looks like LPS-75840 was commited in December, but I could reproduce LPS-74747 in last week's master.

**Comment by robertoDiaz** [comment]
Did you install in your local gifsicle and set the portal to use it?

**Comment by hudakl** [comment]
Could you please elaborate on this question? I'm not yet familiar with Adaptive Media.

**Comment by robertoDiaz** [comment]
@hudakl 

See [Processing Animated GIFs sesction](https://github.com/ngaskill/liferay-docs/blob/a3290d165c27adf6083d913c6a95ac92af8f25b3/discover/portal/articles/03-collaboration/01-managing-documents-and-media/08-adapting-your-media-to-multiple-devices/01-installing-adaptive-media.markdown#processing-animated-gifs-).

Thanks!

**Comment by hudakl** [comment]
I turned the Gifsicle on and the issue is still reproducible.

**Comment by robertoDiaz** [comment]
I've test it and it seems that the cover image is not using Adaptive Media. Anyway, since we have include in master and DXP the gifsicle library I think that be better option is use it and avoid having 2 ways to generate the animated gifs.

I'm going to ask to @sergiogonzalez about this and agree with him how we should fix this (when we talk about this in November gifsicle was not in portal, so I could not suggest it to you before)

I'll update this ticket ASAP

Thanks!

**Comment by robertoDiaz** [comment]
hi @hudakl 

In the original email we decided to:

> From API perspective this is not a blogs issue, it's a ImageTool lack (do not handle the animated gifs) so, in order to fix the issue, and since this could happen in other places in the portal, the best approach is to fix the most generic logic.
> 
> This is why we prefer to avoid introduce changes in (and remove part of the current logic if possible) by making the  ImageTool more "intelligent" allowing handle different logic depending on the mime type of the image.

Since that the logic should not be in the ImageSelectorProcessor but in the ImageTool implementation.

Anyway I've been reviewing de code with @sergiogonzalez and we still consider the solution:

1. very risky due possible performance issues
2. not very clean and maintenable (since it depends in arbitrary conditions)
3. very limited, since only handles the blogs cover image use case and not all the crop posibilities of the portal

Since a SDH was delivered, and we have time to create a nice solution, we prefer to keep it as a limitation by now (the portal is not able to generate animated cropped gifs) than introduce this solution, so please, create a new Feature Request, and pass it to me. I'll move it to collab team PM in order to prioritize it and will be take into account when the Product Team extract the ImageTool logic to a module.

Sorry, because we know that is not the solution you expect, but from a global perspective we think is the best option, taking into account the roadmap of the team.

Best regards.

**Comment by sergiogonzalez** [comment]
Hey guys,
I just closed the LPS ticket related to this https://issues.liferay.com/browse/LPS-74747?focusedCommentId=1232189&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1232189
When you have the feature request please make sure to link it or include it there as well.
Thanks

**Pull request closed without merging**
