### PR TITLE
LPS-80500 Keep the exception handling, as InviteMembersCreateAccountActionProcess may be called twice in a row

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Thanks for the pull.
I re-added the exception handling in `InviteMembersCreateAccountActionProcess`, as `_memberRequestLocalService.updateMemberRequest()` will fail if it is called upon a MemberReques
uest twice.
As `_memberRequestLocalService.updateMemberRequest()` is called by `CreateAccountMVCActionCommand` the first time, the MemberRequest will be already used when login process calls it a second time.

I also made some SF and depencency fixes.

If you find it OK, I'll send it to Sergio.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
We could create a new getMemberRequest method that uses the key, the user and the status, and if it exist, return or continue. It is more explicit and has more semantic than use the exception handling

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Was you able to check if the proposals I made in the last comments are right??

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I found that the status of the `membeRequest` is InviteMembersConstants.STATUS_PENDING (0) at both calls to `_memberRequestLocalService.updateMemberRequest()` so querying for the status would make no difference.

The exception, which is a `MemberRequestInvalidUserException` is thrown when the `memberRequest` is validated against userId 0.

```
validate(memberRequest, 0);
...
		if (memberRequest.getStatus() !=
				InviteMembersConstants.STATUS_PENDING) {

			throw new MemberRequestAlreadyUsedException();
		}
		else if (memberRequest.getReceiverUserId() != userId) {
			throw new MemberRequestInvalidUserException();
		}
```

The `receiverUserId` of of the `membeRequest` will be 0 at the first validation (external user), but it will have it's value set to an existing user's ID at the second validation. This is the point when the validation fails and the `MemberRequestInvalidUserException` gets thrown.

**Comment by IstvanD** [comment]
hey @robertoDiaz 

I added logic that checks if the receiverUserId of the membeRequest is 0. If it is not the case (which indicates that the membeRequest is already processed in the previous call) it returns from the method.
17f0012

Please let me know what you think of this approach.

Best regards,
István

**Comment by robertoDiaz** [comment]
Hi, 

This days I'm handling a critical issue, so I do not have time to check this ticket. I'll come back to it as soon as I have bandwith.

Sorry for the inconveniences bro.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/67. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/3273d32abd39~4...3273d32abd39) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
