### PR TITLE
LPS-89978 Assets publisher's Blog entry popup window doesn't close when an image is uploaded

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

I added logic that ensures that when a new Blog Entry gets published, the dialog gets redirected.

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

It seems that the fix is not the proper one:

1. It doesn't solve the issue when updating the blog entry using asset publisher
2. Why do we need this logic here and not in KB or journal when we do the same? (in kb we could upload files when updating the article)

Was you able to understand the root cause of this bug?? If you did, please, share with me your findings in order to understand it.

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

1. based on the behavior of the Blogs portlet without the Asset Publisher, when a Blog post is updated, the portlet stays on the Edit Blog Entry page, without redirecting to the Blog Entry listing. In my opinion, the behavior should be same on AP
2. in KB, the "javax.portlet.init-param.always-send-redirect=true" is set on the portlet classes. This cannot be done for Blogs because, as stated above, the portlet should only be redirected if a new entry is created.

The cause the of the issue is that the session message "requestProcessed" get inserted into SessionMessages if an image is inserted to the content that was selected from the 'Upload Image' Tab.
You can see that in LiferayPortlet.processAction(), the page will only be redirected if either

1. SessionMessages is empty
2. the always-send-redirect init parameter is set to true.

https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/LiferayPortlet.java#L112-L116

I hope this helps to understand the root cause and the rationale of the solution.

Bests,
István

**Comment by robertoDiaz** [comment]
Thank you for the update:

> based on the behavior of the Blogs portlet without the Asset Publisher, when a Blog post is updated, the portlet stays on the Edit Blog Entry page, without redirecting to the Blog Entry listing. In my opinion, the behavior should be same on AP

I could not see that in my test: If I update the blogs entry **in a public page**, I'm redirected to the blog entries list. Can you explain me the behavior you are seeing??

Anyway, with the current PR, if I:

1) Start server and login as Admin. 
2) Place 'Asset Publisher' portlet on a page. 
3) Add a new blogs entry and save it (using AP or not) and I edit it
4) Click on '+' icon in the editor, and select the Add Image button. 
7) Navigate to 'Upload Image' Tab. 
8) Select any file to upload and click on 'Add' button. 
9) Click on 'Publish' button.

I could find the same error as described: Blog Entry saved and blogs list render in the same popup window.

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I have checked the behavior on master again.
Strangely, now if I update a Blog entry, the portlet get's redirected to the listing. This happens with or without AP involved.

I have updated the solution to reflect this behavior and will send in a separate pull request.

Best regards,
István

**Pull request closed without merging**
