### PR TITLE
LPS-89421 Resized image has poor quality

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

By adding the proper rendering hints, the scaled image will have a much better quality.
I added the rendering hints to the branch that doesn't uses the progressive bi-linear scaling algorithm, since that method produces a decent quality scaling by default.

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

One question.

Why did you select this three keys and did not use, for example KEY_COLOR_RENDERING, KEY_ALPHA_INTERPOLATION ??

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz,

I only used the rendering hints which are the most frequently used in examples.
I chose to include only those because including more of them might impact the performance and speed of the rendering process.

The ideas were taken from these examples:
https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality
https://componenthouse.com/2008/02/08/high-quality-image-resize-with-java/
https://www.journaldev.com/615/java-resize-image

Best regards,
István

**Comment by robertoDiaz** [comment]
Hey @IstvanD 
I've also seen that we could use external libraries to handle this (Thumbnailator, Imgscalr, Morten Nobel's are mentioned in the articles)

Maybe we could provide the current implementation as SDH for the current customer, but as final solution we could use this libraries. @adolfopa is ok with this approach, so if you are able to handle this, please send a new PR with this changes.

Could you handle that?

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Some time ago, I have dealt with similar issue, where the problem was that the generated thumbnails had poor quality.
I have submitted a solution that outsources the scaling process to Thumbnailator. However, it was told me that we should refrain from using third party libraries and try to solve the issues in our own code, where it is possible.
https://github.com/Preston-Crary/liferay-portal/pull/191#issuecomment-251160131

After receiving this answer, I have extracted the progressive bi-linear scaling algorithm from Thumbnailator and applied in the Liferay code.

I'm aware that we have more leeway to utilize third party libraries in modules. However, our image scaling logic is located in `ImageToolImpl.java`, which is a core class. Moving the scaling logic from this class into a module would we a task for which I currently don't have the necessary bandwidth.

On the other hand, if the current solution that utilizes the rendering hints will remain as an SDH, the customer will eventually ask the solution to be released to them in a fix-pack.

Should this solution really not be committed to the product?

Thanks and best regards,
István

**Comment by robertoDiaz** [comment]
Since this part of the code is owned by the Collab team, I'm going to ask @adolfopa and agreed a solution with him.

I'll come back with our conclusions.

Thanks!!

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

In this case, it seems that it was rejected because this library was abandoned.

If we could find a similar one with recent activity and with the right licenses we could use it

Can you check if there are "alive" alternatives to Thumbnailator??

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

As I see, there are no Java based image scaling libraries that are actively developed and/or free
https://github.com/rkalla/imgscalr
http://www.imageresize4j.com/

**Comment by robertoDiaz** [comment]
Ok, I'll move the code to @adolfopa and we'll double check that
Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Sure. I'm looking forward to your responses.

**Comment by robertoDiaz** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/799. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
