### PR TITLE
LPS-50602 Move social logic into updateStatus

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32269. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
