### PR TITLE
[TECH SUPPORT] LPS-72612 Moving (renaming) a Wiki page removes all categories and tags

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this PR:
https://issues.liferay.com/browse/LPS-72612
https://github.com/dsanz/liferay-portal/pull/68

Thanks!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @rimisaadouwork 

Code looks fine, but could you add some tests in [/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/service/test/WikiPageLocalServiceTest.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/service/test/WikiPageLocalServiceTest.java) and resend??

For example checking that the asset entry categories and tags work as expected on renaming (maybe adding new asserts after testRenamePage method could do the trick)

If you need any help, tell me.

Thanks!!!

**Comment by rimisaadouwork** [comment]
Hi @robertoDiaz ,

I updated the code by adding test to it. See PR:
https://github.com/robertoDiaz/liferay-portal/pull/548

Thanks!

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/549. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
