### PR TITLE
master-sc-348

### PR DESCRIPTION
**Pull request by sharonchoi**
@robertoDiaz here's the PR with the poshi test fixes. I think I found a bug, where the text disappears after a user enters content, and then changes the formatting. There's also a javascript error when clicking on the the alloyeditor toggle source button.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi Sharon, i think this is not a but a limitation. We could dicuss that on
monday

Thanks!

**Comment by sharonchoi** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2795. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
