### PR TITLE
LPS-79141 Testing DL File Entry link

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I added a test case to `XhtmlTranslationVisitorTest` however, I'm not sure if the test link has the correct format eg. if it has to contain an actual UUID.

I'LL make corrections where necessary.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
@IstvanD 

Thank you so much 👍

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/58. [See changes here.](https://github.com/robertoDiaz/liferay-portal/compare/cb34291e12d5~2...cb34291e12d5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
