### PR TITLE
LPS-70277 Don't use Non-breaking space in Wiki title

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

It is forwarded from https://github.com/IstvanD/liferay-portal/pull/27

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3752. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
