### PR TITLE
LPS-88064 Tooltip message for Enable Directory Indexing is not correct

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?
Please see the explanation in [LPS-88064](https://issues.liferay.com/browse/LPS-88064)

I changed to tooltip message to reflect the fact that not only site administrators can browse the documents but anyone who has VIEW permission on them.

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

As explained in https://loop.liferay.com/web/guest/home/-/loop/feed/14955839 I was on vacation. I'll try to review this today or tomorrow.

Thanks!!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have seen the notification in the meanwhile, sorry.
The pull request is now at @adolfopa.

Should I send it to you?

Best regards,
István

**Comment by robertoDiaz** [comment]
No, it's ok, but please, assign it to him.

Thanks!

**Comment by IstvanD** [comment]
Sure.
I have opened the pull on Friday.
https://github.com/adolfopa/liferay-portal/pull/759

**Pull request closed without merging**
