### PR TITLE
LPS-85733 Link to documents in Wiki (MediaWiki type) are not correctly updated after > Liferay Wiki import page

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

I created a solution that translates MediaWiki `[[Media:...]]` tags into Creole `[[...]] ` link tags that contain an attachmentURL to the attachments of the SharedImages page.

The reproduction steps are in https://issues.liferay.com/browse/LPS-85733

Could you please check it, and perhaps forward it to the PT?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Sure.

Best regards,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

MediaWikiToCreoleTranslatorTest tests the MediaWikiToCreoleTranslator class, but the fix is implemented as a protected method in MediaWikiImporter.

The reason for this is that in order to create the attachment URL, the method needs a reference to the Wiki Node and also calls other Wiki related APIs. On the other hand, MediaWikiToCreoleTranslator is a plain text processing class.
Is there a preferred way to get around this? Should MediaWikiToCreoleTranslator be changed to be aware of the Wiki Node?

Thanks!

Best regards,
István

**Comment by robertoDiaz** [comment]
Mmmm

I see. I think that we should try to move the logic to MediaWikiToCreoleTranslator, since all this logic is, in fact, creating creole markup (so  the mediawikiimporter doesn't seem to be the right place to put this code since the scope of this class is agnostic from format)

> Should MediaWikiToCreoleTranslator be changed to be aware of the Wiki Node?

Yes. To do so,  we could create a new set to pass the nodeId to the MediaWikiToCreoleTranslator.

Anyway, you could send the original fix to the customer as SDH, taking into account that the final fix could differ from it.

If you need help, please tell me.

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Are you able to handle the requested changes??

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Yes, I'm working on the tests.

**Comment by robertoDiaz** [comment]
Thank you for the update 👍

**Pull request closed without merging**
