### PR TITLE
LPS-107018 No friendly url generated for web content when two locales share same title

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @robertoDiaz, 

This pr has been in my backlog for a while. 

I've update the pr in #33 to take into account the new column `ctCollectionId` for the upgrade step (adding missing friendly url translations that do exist in JournalArticleLocalization). 

The solution's logic remains the same: checking that the friendly url for web contents will be unique taking language into account, so there won't be two web contents in the same group with the same friendly url; and for a single web content, different locales will get different friendly urls. 

When adding the tests I tried using the annotation DataGuard to handle clean-up but it doesn't fully work, thus the longer commit comment explaining this. 

I've also added a message informing the user that friendly urls may be modified to make them unique. 

Please let me know if there's something I should improve or correct. Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by robertoDiaz** [comment]
Hey @ricardocousolr 

Rebase error :(

Could you update the PR??

Thanks!!

**Comment by ricardocousolr** [comment]
Sent rebased pr as #860.

**Pull request closed without merging**
