### PR TITLE
LPS-98654 Image Thumbnail indexes should be taken into account

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

Thank you for the pr, but this is not the idea we have agreed and I explain in the PTR.

What we want is allow users to configure the AMConfiguration they would like to use as thumbnail index for each case.

As an example, in AMConfiguration.java -used in system settings- (or in a similar class) create new field to set the title or the id of the configuration and the thumbnailIndex. Once configured, we could get this configuration based in the value of this field, and return the image.

As said, in the upgrade process we generate some AMConfigurations in an upgrade, based in the values of each thumbnail index. We also have to configure this field with every generated configuration.

Do you have any question about the expected behavior?

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I think I understand what is the intention.

I would go about to create a new configuration class - like AMCustomThumbnailConfiguration - with four numeric fields: thumbnailCustom1MaxHeight, thumbnailCustom1MaxWidth, thumbnailCustom1MaxHeight, thumbnailCustom2MaxWidth.
This would be configurable in System Settings > Adaptive Media > Custom Thumbnail Resolutions.

However, I don't know what method I could use to synchronize these settings with the AM Configurations.
If I save the configurations in System Settings, how should the creation/update of the two AM Configuration (say, CustomThumbnail1 and CustomThumbnal2) be triggered?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

We don´t need numeric fields. We need 3 text fields with:

thumbnailAMConfiguration
thumbnailCustom1AMConfiguration
thumbnailCustom2AMConfiguration

and in each field we could add the desired AMConfiguration Id or title.

Once we do this,  in the  _getThumbnailAdaptiveMedia  we could return the stream of the file using  the index parameter. With this parameter we could get the right configuration and obtain the stream of the fileVersion.

Does it solve your questions?

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Thanks, I think I understand it now.
I'm starting to implement it.
I'll come back if I have any further questions.

Best regards,
István

**Comment by robertoDiaz** [comment]
@IstvanD  👍

**Pull request closed without merging**
