### PR TITLE
LPS-76922 Subscribed user can not receive notification or Email in blogs portlet

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @robertoDiaz 

Could you please check this pull request?

The issue is, that in case of a scheduled publishing, the `entryURL` is not added to the `workflowContext`.

```
protected void notifySubscribers(
		long userId, BlogsEntry entry, ServiceContext serviceContext,
		Map<String, Serializable> workflowContext)
	throws PortalException {

	String entryURL = (String)workflowContext.get(
		WorkflowConstants.CONTEXT_URL);  => null

	if (!entry.isApproved() || Validator.isNull(entryURL)) {
		return;
	}
```

During scheduled release, `BlogsEntryLocalServiceImpl.checkEntries()` traverses through the entries, but does not adds the entryURLs to `workflowContext`.

Adding the call

```
		workflowContext.put(
			WorkflowConstants.CONTEXT_URL, getEntryURL(entry, serviceContext));
```

sets only a blank string because `getEntryURL(entry, serviceContext)` returns immediately when `serviceContext`'s `request` object is not existing.

So my solution is to calculate the `entryURL` in `notifySubscribers()` if it is black.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
@IstvanD 

Did you test it using the control panel portlet??

Can you perform this test?

1. Create a new user and add it as user to a site (no access to control panel at all)
2. Subscribe him to blogs
3. As admin, via control panel create a new entry and publish it.
4. Check if the user has access to the link in the mail (i think that this link is going to be a control panel link and the user could not use it)

Share the results

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

I have tested with the steps above.

In both cases (instat scheduled publication), the entry URL will contain the name of the page where the Blogs portlet is present for which the user subscribed.

For example, if the user subscribed to a Blogs portlet which is on a page called PageA, the URL will look like this:

http://localhost:8080/web/guest/pagea/-/blogs/36621

When the user clicks on this link, the newly added blog entry will be displayed on PageA.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4173. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
